export type Question = {
  id: number;
  category: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  image?: string;
};

export const categories = [
  { id: "segnali", label: "Segnali Stradali", icon: "🚦", color: "from-red-500 to-rose-600" },
  { id: "norme", label: "Norme di Comportamento", icon: "📋", color: "from-blue-500 to-indigo-600" },
  { id: "precedenza", label: "Precedenza", icon: "⚠️", color: "from-yellow-500 to-orange-500" },
  { id: "meccanica", label: "Meccanica & Sicurezza", icon: "🔧", color: "from-green-500 to-emerald-600" },
  { id: "ambiente", label: "Educazione Ambientale", icon: "🌿", color: "from-teal-500 to-cyan-600" },
  { id: "pronto-soccorso", label: "Pronto Soccorso", icon: "🩺", color: "from-pink-500 to-red-500" },
];

export const questions: Question[] = [
  // === SEGNALI STRADALI ===
  {
    id: 1,
    category: "segnali",
    question: "Cosa indica un segnale triangolare con bordo rosso?",
    options: [
      "Un obbligo da rispettare",
      "Un segnale di pericolo",
      "Un divieto assoluto",
      "Un segnale informativo",
    ],
    correct: 1,
    explanation: "I segnali triangolari con bordo rosso sono segnali di pericolo. Avvertono il conducente di un possibile pericolo sulla strada.",
  },
  {
    id: 2,
    category: "segnali",
    question: "Il segnale rotondo con bordo rosso e croce rossa su sfondo bianco indica:",
    options: [
      "Divieto di sosta",
      "Stop – obbligo di fermarsi",
      "Incrocio con precedenza a destra",
      "Divieto di transito",
    ],
    correct: 1,
    explanation: "Il segnale STOP è ottagonale e rosso. Impone l'obbligo assoluto di fermarsi prima di immettersi in un'altra strada.",
  },
  {
    id: 3,
    category: "segnali",
    question: "Cosa significa il segnale triangolare con punto esclamativo?",
    options: [
      "Pericolo generico",
      "Divieto di sorpasso",
      "Obbligo di cedere la precedenza",
      "Lavori in corso",
    ],
    correct: 0,
    explanation: "Il triangolo con punto esclamativo indica un pericolo generico non specificato da altri segnali. Bisogna procedere con prudenza.",
  },
  {
    id: 4,
    category: "segnali",
    question: "Il segnale blu rotondo con freccia bianca indica:",
    options: [
      "Divieto di svoltare",
      "Direzione obbligatoria",
      "Rotatoria obbligatoria",
      "Corsia preferenziale",
    ],
    correct: 1,
    explanation: "I segnali rotondi blu con freccia bianca indicano una direzione obbligatoria che il conducente deve seguire.",
  },
  {
    id: 5,
    category: "segnali",
    question: "Cosa indica il segnale giallo con una freccia nera che piega a destra?",
    options: [
      "Divieto di svolta a destra",
      "Curva pericolosa a destra",
      "Obbligo di svoltare a destra",
      "Deviazione temporanea a destra",
    ],
    correct: 1,
    explanation: "Il triangolo giallo (o bianco bordato di rosso) con freccia indica una curva pericolosa nella direzione indicata dalla freccia.",
  },
  {
    id: 6,
    category: "segnali",
    question: "Il segnale quadrato blu con la lettera 'H' bianca indica:",
    options: [
      "Hotel",
      "Ospedale",
      "Area di sosta",
      "Stazione di rifornimento",
    ],
    correct: 1,
    explanation: "La 'H' su sfondo blu indica un ospedale nelle vicinanze. In queste zone è necessario mantenere il silenzio e la massima prudenza.",
  },
  // === NORME DI COMPORTAMENTO ===
  {
    id: 7,
    category: "norme",
    question: "Qual è il limite di velocità generico sulle autostrade italiane?",
    options: [
      "110 km/h",
      "120 km/h",
      "130 km/h",
      "150 km/h",
    ],
    correct: 2,
    explanation: "Il limite di velocità massima sulle autostrade è 130 km/h. In caso di pioggia o neve il limite si riduce a 110 km/h.",
  },
  {
    id: 8,
    category: "norme",
    question: "Qual è il tasso alcolico massimo consentito per i conducenti normali in Italia?",
    options: [
      "0,0 g/l",
      "0,5 g/l",
      "0,8 g/l",
      "1,0 g/l",
    ],
    correct: 1,
    explanation: "Il tasso alcolemico massimo consentito per i conducenti normali è 0,5 g/l. Per i neopatentati (primi 3 anni) e i conducenti professionali è 0,0 g/l.",
  },
  {
    id: 9,
    category: "norme",
    question: "Quando è obbligatorio l'uso delle luci di posizione?",
    options: [
      "Solo di notte",
      "In galleria, di notte e in condizioni di scarsa visibilità",
      "Solo in galleria",
      "Solo quando piove",
    ],
    correct: 1,
    explanation: "Le luci di posizione (e i fari) sono obbligatorie di notte, in galleria, e in qualsiasi situazione di scarsa visibilità (nebbia, pioggia intensa, neve).",
  },
  {
    id: 10,
    category: "norme",
    question: "La cintura di sicurezza è obbligatoria:",
    options: [
      "Solo per il conducente",
      "Solo in autostrada",
      "Per tutti i passeggeri su tutti i sedili",
      "Solo per i sedili anteriori",
    ],
    correct: 2,
    explanation: "La cintura di sicurezza è obbligatoria per tutti gli occupanti del veicolo, su tutti i sedili (anteriori e posteriori), su qualsiasi tipo di strada.",
  },
  {
    id: 11,
    category: "norme",
    question: "Qual è il limite di velocità in centro abitato?",
    options: [
      "30 km/h",
      "50 km/h",
      "70 km/h",
      "90 km/h",
    ],
    correct: 1,
    explanation: "Il limite di velocità nei centri abitati è 50 km/h, salvo diversa segnalazione. In alcune zone potrebbe essere ridotto a 30 km/h.",
  },
  {
    id: 12,
    category: "norme",
    question: "È consentito usare il cellulare mentre si guida?",
    options: [
      "Sì, se si usa il vivavoce",
      "Sì, se si è fermi al semaforo",
      "No, è sempre vietato tenerlo in mano",
      "Sì, per brevi conversazioni",
    ],
    correct: 2,
    explanation: "È vietato usare il cellulare tenendolo in mano mentre si guida. È consentito solo con auricolare o sistema vivavoce integrato nel veicolo.",
  },
  // === PRECEDENZA ===
  {
    id: 13,
    category: "precedenza",
    question: "In un incrocio senza segnali, a chi si dà la precedenza?",
    options: [
      "A chi viene da sinistra",
      "A chi viene da destra",
      "A chi arriva per primo",
      "Al veicolo più grande",
    ],
    correct: 1,
    explanation: "In assenza di segnali, si deve dare la precedenza ai veicoli che provengono da destra (regola della precedenza a destra).",
  },
  {
    id: 14,
    category: "precedenza",
    question: "Chi ha la precedenza in una rotatoria?",
    options: [
      "Chi entra nella rotatoria",
      "Chi è già nella rotatoria",
      "Chi viene da destra",
      "Chi ha le frecce accese",
    ],
    correct: 1,
    explanation: "Nella rotatoria hanno la precedenza i veicoli che si trovano già all'interno. Chi vuole entrare deve cedere il passo.",
  },
  {
    id: 15,
    category: "precedenza",
    question: "I veicoli di emergenza con sirena e lampeggiante accesi:",
    options: [
      "Devono rispettare il codice della strada",
      "Hanno sempre la precedenza assoluta",
      "Hanno precedenza solo sulle autostrade",
      "Possono passare con il rosso solo di notte",
    ],
    correct: 1,
    explanation: "I veicoli di soccorso in emergenza (ambulanze, pompieri, polizia) con sirena e lampeggiante accesi hanno sempre la precedenza. Gli altri conducenti devono liberare la carreggiata.",
  },
  {
    id: 16,
    category: "precedenza",
    question: "Quando si incontra un segnale 'Dare precedenza' (triangolo invertito):",
    options: [
      "Ci si deve fermare obbligatoriamente",
      "Si riduce la velocità ma non è obbligatorio fermarsi",
      "Si procede normalmente",
      "Si deve suonare il clacson",
    ],
    correct: 1,
    explanation: "Il segnale di 'Dare precedenza' impone di rallentare e cedere il passo, ma non richiede l'arresto completo come lo STOP, a meno che non ci sia traffico.",
  },
  // === MECCANICA & SICUREZZA ===
  {
    id: 17,
    category: "meccanica",
    question: "Con quale frequenza minima si consiglia di controllare la pressione dei pneumatici?",
    options: [
      "Ogni week",
      "Una volta al mese e prima di lunghi viaggi",
      "Solo al cambio stagione",
      "Solo in caso di foratura",
    ],
    correct: 1,
    explanation: "La pressione dei pneumatici va controllata almeno una volta al mese e prima di ogni lungo viaggio, possibilmente a freddo.",
  },
  {
    id: 18,
    category: "meccanica",
    question: "Cosa indica la spia rossa a forma di batteria sul cruscotto?",
    options: [
      "Batteria scarica",
      "Problema al sistema di ricarica dell'alternatore",
      "Livello olio basso",
      "Freno a mano inserito",
    ],
    correct: 1,
    explanation: "La spia della batteria rossa indica un problema al sistema di ricarica. Solitamente segnala un guasto all'alternatore. Fermarsi appena possibile.",
  },
  {
    id: 19,
    category: "meccanica",
    question: "Quando si deve usare la marcia più bassa in discesa?",
    options: [
      "Mai, basta frenare",
      "Sempre, per mantenere il controllo del veicolo",
      "Solo se la discesa è ripida e lunga",
      "Solo su strade bagnate",
    ],
    correct: 2,
    explanation: "In discese ripide e lunghe, si deve inserire una marcia bassa per sfruttare il freno motore ed evitare il surriscaldamento dei freni.",
  },
  {
    id: 20,
    category: "meccanica",
    question: "Cosa si deve fare in caso di foratura mentre si è in marcia?",
    options: [
      "Frenare bruscamente e fermarsi",
      "Tenere saldamente il volante, accelerare e poi frenare",
      "Tenere saldamente il volante, non frenare bruscamente e portare il veicolo a lato della strada",
      "Spegnere il motore immediatamente",
    ],
    correct: 2,
    explanation: "In caso di foratura, bisogna tenere il volante con entrambe le mani, non frenare bruscamente, lasciare che il veicolo rallenti gradualmente e portarsi a bordo strada in sicurezza.",
  },
  // === AMBIENTE ===
  {
    id: 21,
    category: "ambiente",
    question: "In quale zona è solitamente vietato circolare ai veicoli più inquinanti?",
    options: [
      "ZTL (Zona a Traffico Limitato)",
      "ZES (Zona Economica Speciale)",
      "ZPE (Zona di Protezione Ecologica)",
      "ZAU (Zona Autovetture Unificate)",
    ],
    correct: 0,
    explanation: "Le ZTL (Zone a Traffico Limitato) nelle città limitano o vietano l'accesso ai veicoli più vecchi o inquinanti, specialmente nei periodi di alta concentrazione di smog.",
  },
  {
    id: 22,
    category: "ambiente",
    question: "Cosa significa la classificazione 'Euro 6' per un veicolo?",
    options: [
      "Il veicolo ha 6 cilindri",
      "Il veicolo rispetta gli standard europei più recenti sulle emissioni",
      "Il veicolo ha 6 anni di vita",
      "Il veicolo può circolare in 6 paesi europei",
    ],
    correct: 1,
    explanation: "La classificazione Euro indica il livello di emissioni inquinanti del veicolo. Euro 6 è lo standard più severo attualmente in vigore nell'Unione Europea.",
  },
  // === PRONTO SOCCORSO ===
  {
    id: 23,
    category: "pronto-soccorso",
    question: "Qual è il numero unico di emergenza europeo?",
    options: [
      "112",
      "118",
      "113",
      "115",
    ],
    correct: 0,
    explanation: "Il 112 è il numero unico di emergenza europeo. Funziona in tutta l'UE gratuitamente. In Italia il 118 è specifico per le emergenze sanitarie.",
  },
  {
    id: 24,
    category: "pronto-soccorso",
    question: "In caso di incidente con feriti, cosa si deve fare PRIMA di qualsiasi altra cosa?",
    options: [
      "Spostare i feriti dal veicolo",
      "Chiamare i soccorsi (112/118)",
      "Mettere in sicurezza la scena e segnalare il pericolo",
      "Fotografare la scena",
    ],
    correct: 2,
    explanation: "La prima cosa da fare è mettere in sicurezza la scena (triangolo, luci di emergenza) per evitare ulteriori incidenti. Poi chiamare i soccorsi. Non spostare i feriti salvo pericolo imminente di vita.",
  },
  {
    id: 25,
    category: "pronto-soccorso",
    question: "Come si posiziona correttamente il triangolo di emergenza?",
    options: [
      "A 5 metri dietro il veicolo",
      "A 50 metri dietro il veicolo, in modo da essere visibile a distanza sufficiente",
      "Davanti al veicolo",
      "Sul tetto del veicolo",
    ],
    correct: 1,
    explanation: "Il triangolo va posizionato a circa 30-50 metri dietro il veicolo (più distante in autostrada) per dare agli altri conducenti il tempo di rallentare.",
  },
  {
    id: 26,
    category: "pronto-soccorso",
    question: "Se un ferito è incosciente ma respira, in quale posizione va messo?",
    options: [
      "Sulla schiena con le gambe alzate",
      "In posizione laterale di sicurezza (PLS)",
      "Seduto con la testa inclinata in avanti",
      "Non va spostato in nessun caso",
    ],
    correct: 1,
    explanation: "La posizione laterale di sicurezza (PLS) viene usata per le persone incoscienti che respirano per prevenire il rischio di soffocamento dovuto a vomito o ostruzione delle vie aeree.",
  },
  // === More NORME ===
  {
    id: 27,
    category: "norme",
    question: "Il sorpasso è consentito quando:",
    options: [
      "C'è la striscia continua al centro della carreggiata",
      "C'è la striscia discontinua al centro e si ha visibilità sufficiente",
      "Su qualsiasi strada se non ci sono altri veicoli",
      "Solo su strade a quattro corsie",
    ],
    correct: 1,
    explanation: "Il sorpasso è consentito solo quando al centro c'è una striscia discontinua, c'è sufficiente visibilità, e non si mette in pericolo nessuno.",
  },
  {
    id: 28,
    category: "norme",
    question: "Qual è il limite di velocità sulle strade extraurbane principali?",
    options: [
      "70 km/h",
      "90 km/h",
      "110 km/h",
      "130 km/h",
    ],
    correct: 2,
    explanation: "Il limite di velocità sulle strade extraurbane principali (es. superstrade) è 110 km/h. Sulle strade extraurbane secondarie è 90 km/h.",
  },
  {
    id: 29,
    category: "segnali",
    question: "Un segnale rettangolare blu con freccia bianca verso l'alto indica:",
    options: [
      "Divieto di transito",
      "Corsia preferenziale per mezzi pubblici",
      "Indicazione di distanza o direzione",
      "Zona di sosta",
    ],
    correct: 2,
    explanation: "I pannelli rettangolari blu sono segnali di indicazione, usati per informare su direzioni, distanze e servizi.",
  },
  {
    id: 30,
    category: "precedenza",
    question: "I pedoni che attraversano sulle strisce pedonali:",
    options: [
      "Devono aspettare che passino i veicoli",
      "Hanno sempre la precedenza sui veicoli",
      "Hanno precedenza solo quando il semaforo è verde per loro",
      "Devono aspettare se ci sono più di 3 veicoli in transito",
    ],
    correct: 1,
    explanation: "I pedoni che attraversano sulle strisce pedonali hanno sempre la precedenza. I conducenti sono obbligati a fermarsi e lasciarli passare.",
  },
];
