// ─── Dal Medico — Part 1 (Pages 91–96) ────────────────────────────────────────
import type { ReadingSection } from "@/lib/italiano";

export const dalMedicoPart1: ReadingSection[] = [
  // ── Page 91 ── Tutto per il trofeo
  {
    heading: "Tutto per il trofeo (Pagina 91)",
    headingFa: "همه‌چیز برای جام قهرمانی",
    body: "Giulia chiama uno schema veloce, salta altissima e colpisce la palla con tantissima forza. Il muro avversario non riesce a fermarla: è punto! Ma proprio mentre sta per esultare, succede un disastro. Quando cade a terra, il suo piede finisce sopra quello di un'avversaria che aveva invaso il campo sotto la rete.\n\nSi sente un \"crack\" secco nell'aria. Giulia cade sul pavimento, stringe la caviglia destra e diventa pallidissima per la sofferenza. L'arbitro fischia subito e l'allenatore corre da lei con il ghiaccio istantaneo. La caviglia è già diventata gonfia come un palloncino e fa molto male. Giulia deve lasciare il campo portata a braccia, ma tutto il pubblico si alza in piedi e batte le mani per farle coraggio.\n\nPoco dopo arriva in ospedale ancora con la divisa da gioco addosso. Il medico guarda la radiografia, sorride e la rassicura: \"Niente di rotto, Giulia! Non dobbiamo gessare la gamba. È solo una brutta distorsione, ma dovrai usare i bastoni per tre settimane, mettere tanto ghiaccio e fare fisioterapia\".\n\nMentre esce dall'ospedale camminando piano con i suoi nuovi bastoni, il telefono vibra. È un messaggio della sua squadra: le mandano un selfie con la coppa del primo posto e urlano tutte insieme: \"Questa vittoria è per te!\". Nonostante il dolore, Giulia sorride felice: il trofeo è vinto e lei tornerà presto in campo più forte di prima.",
    bodyFa: "جولیا یه اسکیم سریع اعلام می‌کنه، خیلی بلند می‌پره و با قدرت زیاد توپ رو می‌زنه. دیوار حریف نمی‌تونه جلوش رو بگیره: امتیازه! اما درست وقتی داره خوشحالی می‌کنه، فاجعه رخ می‌ده. وقتی می‌افته زمین، پاش میره رو پای حریفی که زیر تور وارد زمین شده بود.\n\nیه صدای «کراک» خشک تو هوا شنیده می‌شه. جولیا رو زمین می‌افته، مچ پای راستش رو محکم می‌گیره و از درد رنگش می‌پره. داور فوری سوت می‌زنه و مربی با یخ فوری بطرفش می‌دوه. مچ پا از الان مثل بادکنک ورم کرده و خیلی درد می‌کنه. جولیا باید روی دست از زمین خارج بشه، اما همه تماشاچیا بلند می‌شن و برای دلگرمی دست می‌زنن.\n\nکمی بعد با لباس بازی تنش به بیمارستان می‌رسه. دکتر رادیوگرافی رو نگاه می‌کنه، لبخند می‌زنه و خیالش رو راحت می‌کنه: «چیزی نشکسته جولیا! لازم نیست گچ بگیریم. فقط یه پیچ‌خوردگی بده، ولی باید سه هفته عصا بزنی، کلی یخ بذاری و فیزیوتراپی کنی.»\n\nموقع خروج از بیمارستان که آروم با عصاهای جدیدش راه می‌ره، گوشیش زنگ می‌زنه. پیام تیمشه: یه سلفی با جام قهرمانی فرستادن و همه باهم داد می‌زنن: «این پیروزی مال تو!» با وجود درد، جولیا با خوشحالی لبخند می‌زنه: جام رو بردن و اون به زودی قوی‌تر از قبل برمی‌گرده.",
    keywords: ["trofeo","caviglia","distorsione","radiografia","fisioterapia","bastoni","ghiaccio","gessare","coppa"],
  },
  // ── Page 92 ── Il prelievo del sangue
  {
    heading: "Il prelievo del sangue (Pagina 92)",
    headingFa: "خون‌گیری",
    body: "Oggi vado in ospedale per fare un prelievo del sangue. È un esame molto comune e importante per controllare la salute.\nIeri sera ho cenato presto perché oggi devo essere a digiuno: questo significa che non posso mangiare e non posso bere caffè o succhi prima dell'esame. Posso bere solo un po' d'acqua.\nQuando arrivo, l'infermiere mi fa sedere su una sedia comoda. Mi chiede di tirare su la manica della maglia e mi mette un laccio elastico sul braccio. Poi pulisce la pelle con un po' di disinfettante.\nL'infermiere usa un ago piccolo per prendere il sangue. In quel momento sento solo un piccolo pizzico, ma non è molto doloroso. La procedura è molto veloce e dura solo un minuto.\nAlla fine, l'infermiere mette un pezzo di cotone e un cerotto sul mio braccio. Mi consiglia di premere per qualche minuto per non far uscire il sangue. Ora posso andare al bar a fare colazione! I risultati delle analisi saranno pronti tra tre giorni.",
    bodyFa: "امروز می‌رم بیمارستان برای خون‌گیری. این یه آزمایش خیلی رایج و مهم برای بررسی سلامتیه.\nدیشب زود شام خوردم چون امروز باید ناشتا باشم: یعنی نمی‌تونم چیزی بخورم و قبل از آزمایش نمی‌تونم قهوه یا آبمیوه بخورم. فقط می‌تونم یه کم آب بخورم.\nوقتی می‌رسم، پرستار منو رو یه صندلی راحت می‌شونه. ازم می‌خواد آستینم رو بزنم بالا و یه بند کشی رو بازوم می‌بنده. بعد پوست رو با یه کم ضدعفونی‌کننده تمیز می‌کنه.\nپرستار از یه سوزن کوچک برای گرفتن خون استفاده می‌کنه. اون لحظه فقط یه نیشگون کوچک حس می‌کنم، ولی خیلی دردناک نیست. عمل خیلی سریعه و فقط یه دقیقه طول می‌کشه.\nآخرش، پرستار یه تکه پنبه و یه چسب زخم رو بازوم می‌ذاره. بهم توصیه می‌کنه چند دقیقه فشار بدم تا خون نیاد. حالا می‌تونم برم کافه صبحانه بخورم! نتایج آزمایش تا سه روز دیگه آماده می‌شه.",
    keywords: ["prelievo","sangue","digiuno","laccio","ago","disinfettante","cerotto","analisi","infermiere"],
    callout: {
      title: "Esercizio di comprensione",
      items: [
        "Perché il protagonista non fa colazione a casa?",
        "Chi usa l'ago per prendere il sangue?",
        "Cosa mette l'infermiere sul braccio alla fine?",
        "Vuoi che trasformerò questo testo in un dialogo tra un medico e un paziente?",
      ],
    },
  },
  // ── Page 93 ── Andare al medico... Facile o Difficile?
  {
    heading: "Andare al medico... Facile o Difficile? (Pagina 93)",
    headingFa: "رفتن به دکتر... آسان یا سخت؟",
    body: "C'era una volta Marco, un uomo che evitava i medici come se fossero portatori di sfortuna. Un giorno, però, un dolore fastidioso alla spalla lo convinse che era ora di farsi controllare.\nArrivato in sala d'attesa, si sedette vicino a una signora che leggeva una rivista del 2012 e a un bambino che giocava con un robot rumoroso. Dopo quaranta minuti di attesa, finalmente sentì chiamare il suo nome: \"Signor Marco, prego!\".\n\nEntrato nello studio, il dottore lo guardò sopra gli occhiali. \"Dunque, Marco, cosa ci porta qui oggi?\". Marco spiegò il dolore alla spalla, cercando di sembrare coraggioso. Il medico iniziò a visitarlo: \"Respiri profondamente... ancora... bene\". Poi arrivò il momento temuto: il riflesso del ginocchio. Il dottore colpì con il martelletto e la gamba di Marco scattò così forte da colpire quasi il povero medico al mento. \"Riflessi eccellenti!\" esclamò il dottore, ridendo sotto i baffi.\n\nDopo aver prescritto una crema e un po' di riposo, il medico aggiunse:\n\"E cerchi di non sollevare pesi per una settimana\". Marco dice di sì con la testa. È felice perché la visita è finita. Ma, mentre esce dalla stanza, cade sopra il tappeto dello studio.\nMolti fogli cadono dalla scrivania del dottore. Marco diventa rosso in faccia per la vergogna.\n\n\"Tutto bene?\" chiese il medico.\n\"Sì, sì!\" rispose Marco arrossendo. \"Volevo solo testare anche i miei riflessi da caduta!\"\nUscì dalla clinica con la sua ricetta in mano, pensando che, dopotutto, andare dal medico non era poi così male, a patto di non prendere a calci nessuno.",
    bodyFa: "روزی روزگاری مارکو بود، مردی که از دکترها مثل حاملان بدشانسی فرار می‌کرد. اما یه روز یه درد آزاردهنده تو شونه‌ش قانعش کرد که وقتشه بره معاینه.\nوقتی رسید سالن انتظار، نشست کنار خانمی که مجله سال ۲۰۱۲ می‌خوند و بچه‌ای که با ربات پر سروصدا بازی می‌کرد. بعد از چهل دقیقه انتظار، بالاخره اسمش رو صدا زدن: «آقای مارکو، بفرمایید!»\n\nوقتی وارد مطب شد، دکتر از بالای عینکش نگاهش کرد. «خب مارکو، چی شده امروز اومدی؟» مارکو درد شونه‌ش رو توضیح داد و سعی کرد شجاع به نظر برسه. دکتر شروع کرد به معاینه: «نفس عمیق بکشید... بازم... خوبه.» بعد لحظه ترسناک رسید: رفلکس زانو. دکتر با چکش زد و پای مارکو اونقدر محکم پرید که نزدیک بود بخوره تو چونه بیچاره دکتر. «رفلکس‌های عالی!» دکتر با خنده زیر سبیلی گفت.\n\nبعد از تجویز کرم و کمی استراحت، دکتر اضافه کرد:\n«و سعی کنید یه هفته چیز سنگین بلند نکنید.» مارکو با سر تأیید کرد. خوشحاله که ویزیت تموم شد. اما موقع خروج از اتاق، می‌افته رو فرش مطب.\nکلی کاغذ از میز دکتر می‌ریزه. صورت مارکو از خجالت قرمز می‌شه.\n\n«حالتون خوبه؟» دکتر پرسید.\n«بله، بله!» مارکو با خجالت جواب داد. «فقط می‌خواستم رفلکس‌های افتادنم رو هم تست کنم!»\nاز کلینیک با نسخه تو دستش خارج شد و فکر کرد، بالاخره رفتن پیش دکتر اونقدرا هم بد نیست، به شرطی که به کسی لگد نزنی.",
    keywords: ["sala d'attesa","riflesso","ginocchio","martelletto","crema","ricetta","tappeto","vergogna"],
  },
  // ── Page 94 ── Un mercoledì a letto
  {
    heading: "Un mercoledì a letto (Pagina 94)",
    headingFa: "یک چهارشنبه در تخت",
    body: "C'era una volta Luca, che si sentiva indistruttibile finché un mercoledì mattina si svegliò con la sensazione di avere un sacco di sabbia al posto della testa. Il raffreddore era arrivato così forte che il suo naso sembrava una fontana aperta e gli occhi gli lacrimavano come se avesse appena finito di guardare il film più triste del mondo.\nProvò a misurare la temperatura e il termometro emise un bip spietato: 39.2°C. La febbre alta lo faceva sentire come se stesse camminando sulle nuvole, ma in modo decisamente poco piacevole.\nDecise di andare dal medico, ma già solo infilarsi i calzini sembrò un'impresa degna di un atleta olimpico. Arrivato in studio, avvolto in una sciarpa che lo faceva somigliare a una mummia, Luca non riusciva a smettere di starnutire. Uno dei suoi starnuti fu così potente che il signore seduto di fronte a lui chiuse l'ombrello per riflesso.\nFinalmente entrò dal dottore.\n\"Dottore,\" disse Luca con una voce che sembrava quella di un citofono rotto, \"credo di aver preso un virus... o forse un intero esercito di virus.\"\nIl medico lo visitò, gli guardò la gola (rossa come un peperoncino) e sospirò: \"Caro Luca, qui non servono miracoli, serve solo molto riposo, tanta acqua e tachipirina. Il tuo corpo sta combattendo una battaglia epica.\"\nMentre tornava a casa, Luca si fermò in farmacia. Con la mente annebbiata dalla febbre, invece di chiedere le caramelle al miele, chiese delle \"caramelle al merluzzo\". Il farmacista lo guardò perplesso, ma Luca era troppo impegnato a cercare un fazzoletto per accorgersi della gaffe.\nTornato a letto, si immerse sotto tre piumini, con una tazza di brodo caldo e una montagna di fazzoletti usati che ormai formavano una piccola catena montuosa sul comodino. Nonostante la testa pesante, pensò: \"Almeno oggi il mio unico lavoro è dormire.\"",
    bodyFa: "روزی روزگاری لوکا بود، که احساس شکست‌ناپذیری می‌کرد تا اینکه یه صبح چهارشنبه با احساس داشتن یه کیسه شن به جای سرش بیدار شد. سرماخوردگی اونقدر شدید اومده بود که بینیش مثل شیر آب باز بود و چشماش اشک می‌ریختن انگار تازه غمگین‌ترین فیلم دنیا رو تموم کرده بود.\nسعی کرد دماش رو بگیره و دماسنج یه بیپ بی‌رحمانه زد: ۳۹.۲ درجه. تب بالا حسی بهش می‌داد انگار رو ابرا راه می‌ره، ولی به شکلی اصلاً خوشایند نبود.\nتصمیم گرفت بره دکتر، ولی فقط پوشیدن جوراب مثل یه چالش المپیکی بود. وقتی رسید مطب، پیچیده تو شالی که شبیه مومیایی شده بود، لوکا نمی‌تونست عطسه کردن رو متوقف کنه. یکی از عطسه‌هاش اونقدر قوی بود که آقای روبروییش از روی رفلکس چترش رو بست.\nبالاخره وارد اتاق دکتر شد.\n«دکتر،» لوکا با صدایی شبیه آیفون خراب گفت، «فکر کنم یه ویروس گرفتم... یا شاید یه ارتش کامل ویروس.»\nدکتر معاینه‌اش کرد، گلوش رو نگاه کرد (قرمز مثل فلفل) و آه کشید: «لوکای عزیز، اینجا معجزه لازم نیست، فقط خیلی استراحت، آب زیاد و تاکی‌پیرینا لازمه. بدنت داره یه نبرد حماسی می‌کنه.»\nموقع برگشت خونه، لوکا تو داروخونه ایستاد. با ذهن مه‌آلود از تب، به جای آبنبات عسلی، «آبنبات ماهی» خواست. داروساز گیج نگاهش کرد، ولی لوکا خیلی مشغول پیدا کردن دستمال بود که متوجه سوتی‌اش بشه.\nبرگشت تو تخت، رفت زیر سه تا لحاف، با یه فنجان آبگوشت داغ و کوهی از دستمال‌های استفاده‌شده که حالا رو پاتختی یه رشته‌کوه کوچک ساخته بودن. با وجود سنگینی سرش فکر کرد: «حداقل امروز تنها کارم خوابیدنه.»",
    keywords: ["raffreddore","termometro","febbre","starnutire","tachipirina","farmacia","brodo","fazzoletti","mummia"],
  },
  // ── Page 95 ── La partita di calcio
  {
    heading: "La partita di calcio — Una caduta in campo (Pagina 95)",
    headingFa: "مسابقه فوتبال — افتادن در زمین بازی",
    body: "Sabato scorso, Marco giocava a calcetto con i suoi amici al parco. Era una bella giornata di sole e tutti si divertivano. Marco correva veloce con la palla quando, improvvisamente, è scivolato sull'erba bagnata e è caduto male sulla gamba destra.\n\nHa sentito un dolore fortissimo al ginocchio e non riusciva a stare in piedi. I suoi amici lo hanno aiutato a sedersi sulla panchina e gli hanno messo del ghiaccio sulla gamba. Il ginocchio era molto gonfio e rosso.\n\nMarco è andato al pronto soccorso. Il medico lo ha visitato e gli ha fatto una radiografia. Per fortuna non c'era nessuna frattura, solo una brutta contusione. Il medico gli ha prescritto una pomata antinfiammatoria e gli ha detto di tenere la gamba a riposo per almeno una settimana.\n\nOra Marco cammina con una fasciatura al ginocchio e non può giocare a calcetto per un po'. I suoi amici lo prendono in giro: \"La prossima volta, gioca a scacchi!\"",
    bodyFa: "شنبه گذشته مارکو با دوستاش تو پارک فوتسال بازی می‌کرد. روز آفتابی قشنگی بود و همه خوش می‌گذروندن. مارکو سریع با توپ می‌دوید که یهو رو چمن خیس لیز خورد و بد افتاد رو پای راستش.\n\nدرد خیلی شدیدی تو زانوش حس کرد و نمی‌تونست سرپا وایسته. دوستاش کمکش کردن بشینه رو نیمکت و یخ گذاشتن رو پاش. زانوش خیلی ورم کرده و قرمز بود.\n\nمارکو رفت اورژانس. دکتر معاینه‌اش کرد و رادیوگرافی گرفت. خوشبختانه شکستگی نبود، فقط یه کبودی بد. دکتر پماد ضدالتهاب تجویز کرد و گفت حداقل یه هفته پاش رو استراحت بده.\n\nحالا مارکو با باند رو زانوش راه می‌ره و تا مدتی نمی‌تونه فوتسال بازی کنه. دوستاش مسخره‌اش می‌کنن: «دفعه بعد شطرنج بازی کن!»",
    keywords: ["calcetto","ginocchio","ghiaccio","pronto soccorso","radiografia","frattura","contusione","pomata","fasciatura"],
  },
  // ── Page 96 ── Il dentista — Una visita di controllo
  {
    heading: "Il dentista — Una visita di controllo (Pagina 96)",
    headingFa: "دندانپزشک — ویزیت کنترلی",
    body: "Martina non va dal dentista da più di un anno. Sa che deve fare un controllo, ma ha sempre un po' di paura. Oggi, finalmente, ha preso coraggio e ha prenotato un appuntamento.\n\nArriva allo studio dentistico alle 15:00. La sala d'attesa è piccola ma accogliente, con riviste e musica di sottofondo. Dopo dieci minuti, l'assistente la chiama: \"Signora Martina, prego, si accomodi\".\n\nMartina si siede sulla poltrona del dentista. Il dottor Verdi le sorride: \"Apra la bocca e mi faccia vedere\". Il dentista controlla tutti i denti con uno specchietto e una sonda. Martina stringe i braccioli della poltrona per la tensione.\n\n\"Ho una buona notizia e una meno buona\", dice il dentista. \"I denti sono in buone condizioni, ma c'è una piccola carie su un molare. Dobbiamo fare un'otturazione la prossima settimana. Non si preoccupi, sarà veloce e indolore.\"\n\nMartina prenota il prossimo appuntamento e esce sollevata. Pensa: \"Non era poi così terribile!\"",
    bodyFa: "مارتینا بیش از یک سال هست که دندانپزشک نرفته. می‌دونه باید چکاپ کنه، ولی همیشه یه کم می‌ترسه. امروز بالاخره جرأت پیدا کرده و وقت گرفته.\n\nساعت ۱۵ به مطب دندانپزشکی می‌رسه. سالن انتظار کوچیک ولی دنج هست، با مجله و موسیقی ملایم. بعد از ده دقیقه، دستیار صداش می‌کنه: «خانم مارتینا، بفرمایید.»\n\nمارتینا رو صندلی دندانپزشکی می‌شینه. دکتر وردی بهش لبخند می‌زنه: «دهنتون رو باز کنید بذارید ببینم.» دندانپزشک همه دندان‌ها رو با آینه کوچک و سوند بررسی می‌کنه. مارتینا از استرس دسته‌های صندلی رو محکم فشار می‌ده.\n\n«یه خبر خوب دارم و یه خبر کمتر خوب،» دندانپزشک می‌گه. «دندان‌ها وضعیتشون خوبه، ولی یه پوسیدگی کوچک رو یه دندان آسیاب هست. باید هفته بعد پرش کنیم. نگران نباشید، سریع و بدون درد انجام می‌شه.»\n\nمارتینا وقت بعدی رو رزرو می‌کنه و با خیال راحت بیرون میره. فکر می‌کنه: «اونقدرا هم ترسناک نبود!»",
    keywords: ["dentista","controllo","poltrona","specchietto","sonda","carie","molare","otturazione","indolore"],
  },
];
