import type { Question } from "@/lib/types";

export const chapter10Questions: Question[] = [
  { id: 1001, chapter: 10, question: "In caso di incidente stradale con feriti, cosa deve fare il conducente?", options: ["Fermarsi, prestare soccorso e chiamare il 112/118", "Continuare la marcia e chiamare poi", "Fermarsi solo se è responsabile", "Spostare i veicoli e chiamare le autorità"], correct: 0, explanation: "In caso di incidente con feriti il conducente è OBBLIGATO a: fermarsi, prestare soccorso immediato e chiamare i soccorsi (112/118). Fuggire o non prestare soccorso è un reato.", vocab: [{ italian: "obbligo di soccorso", persian: "اجبار کمک‌رسانی" }] },
  { id: 1002, chapter: 10, question: "Qual è il numero unico di emergenza europeo?", options: ["112", "118", "113", "115"], correct: 0, explanation: "Il 112 è il numero unico di emergenza valido in tutta l'Unione Europea. Permette di contattare polizia, ambulanza o vigili del fuoco.", vocab: [{ italian: "numero di emergenza", persian: "شماره اورژانس" }] },
  { id: 1003, chapter: 10, question: "Qual è il numero da chiamare per un'emergenza sanitaria (ambulanza) in Italia?", options: ["118", "112", "115", "113"], correct: 0, explanation: "Il 118 è il numero del Servizio Emergenza Sanitaria (ambulanze). Risponde anche il 112 che poi trasferisce la chiamata al servizio appropriato.", vocab: [{ italian: "118 ambulanza", persian: "۱۱۸ آمبولانس" }] },
  { id: 1004, chapter: 10, question: "I veicoli coinvolti in un incidente devono essere spostati?", options: ["Non devono essere spostati (salvo pericolo), per consentire i rilievi alle autorità", "Devono essere sempre spostati ai bordi della strada", "Devono essere spostati solo se ci sono feriti", "Devono essere spostati prima dell'arrivo della polizia"], correct: 0, explanation: "I veicoli non devono essere spostati (salvo immediato pericolo) per permettere alle autorità di fare i rilievi dell'incidente. Spostare i veicoli senza motivo è sanzionabile.", vocab: [{ italian: "non spostare i veicoli", persian: "وسایل را جابجا نکنید" }] },
  { id: 1005, chapter: 10, question: "Un ferito in un incidente deve essere spostato?", options: ["No, salvo pericolo imminente (rischio di lesioni spinali)", "Sì, sempre per portarlo in un posto sicuro", "Sì, ma solo se è incosciente", "No, mai in nessun caso"], correct: 0, explanation: "I feriti NON devono essere spostati a meno che non ci sia un pericolo imminente (es. incendio), perché uno spostamento errato può aggravare le lesioni, specialmente alla colonna vertebrale.", vocab: [{ italian: "non spostare i feriti", persian: "مجروحان را جابجا نکنید" }] },
  { id: 1006, chapter: 10, question: "Cos'è l'omissione di soccorso?", options: ["Un reato che consiste nel non prestare soccorso a chi è in pericolo", "Una semplice infrazione amministrativa", "Solo applicabile ai medici", "Applicabile solo sulle autostrade"], correct: 0, explanation: "L'omissione di soccorso è un REATO penale. Chi non presta aiuto a una persona in pericolo (anche in incidenti stradali) può essere perseguito penalmente.", vocab: [{ italian: "omissione di soccorso", persian: "ترک صحنه / عدم کمک‌رسانی" }] },
  { id: 1007, chapter: 10, question: "Come si ferma una emorragia in attesa dei soccorsi?", options: ["Applicando pressione diretta sulla ferita con un panno pulito", "Mettendo un laccio molto stretto sopra la ferita", "Lavando la ferita con acqua", "Non si deve toccare la ferita"], correct: 0, explanation: "In caso di emorragia, la prima cosa da fare è applicare pressione diretta e costante sulla ferita con un panno pulito o sterile. Non togliere la pressione. Chiamare il 118.", vocab: [{ italian: "fermare un'emorragia", persian: "متوقف کردن خونریزی" }] },
  { id: 1008, chapter: 10, question: "Cosa si deve fare in caso di incidente senza feriti ma con danni ai veicoli?", options: ["Compilare il modulo CAI (constatazione amichevole) e, se non si raggiunge accordo, chiamare le autorità", "Chiamare sempre la polizia", "Scambiarsi solo i numeri di telefono", "Non è necessario fare nulla se i danni sono lievi"], correct: 0, explanation: "In caso di incidente senza feriti si può compilare il modulo CAI (constatazione amichevole) se si è d'accordo. Se non si raggiunge un accordo, si chiama la polizia.", vocab: [{ italian: "modulo CAI", persian: "فرم اعلام خسارت دوطرفه" }] },
];
