import type { Question } from "@/lib/types";

export const chapter25Questions: Question[] = [
  { id: 2501, chapter: 25, question: "Qual è il limite di velocità nei centri abitati?", options: ["50 km/h", "70 km/h", "30 km/h", "90 km/h"], correct: 0, explanation: "Il limite generale nei centri abitati è 50 km/h.", vocab: [{ italian: "centro abitato", persian: "داخل شهر" }] },
  { id: 2502, chapter: 25, question: "Qual è il punteggio iniziale della patente a punti?", options: ["20 punti", "10 punti", "30 punti", "15 punti"], correct: 0, explanation: "La patente a punti ha un punteggio iniziale di 20 punti. Se scende a zero la patente viene revocata.", vocab: [{ italian: "patente a punti", persian: "گواهینامه امتیازی" }] },
  { id: 2503, chapter: 25, question: "Di quanti punti viene ripristinato il punteggio patente ogni anno senza infrazioni?", options: ["2 punti", "5 punti", "1 punto", "3 punti"], correct: 0, explanation: "Ogni anno senza infrazioni si recuperano 2 punti sulla patente, fino al massimo di 20.", vocab: [{ italian: "recupero punti", persian: "بازیابی امتیاز" }] },
  { id: 2504, chapter: 25, question: "Qual è il limite alcolemico per i neopatentati?", options: ["0 g/l (zero)", "0,5 g/l", "0,2 g/l", "0,3 g/l"], correct: 0, explanation: "Per neopatentati, under 21 e conducenti professionali il limite è zero tolleranza.", vocab: [{ italian: "neopatentati alcol", persian: "نوپاتنت و الکل" }] },
  { id: 2505, chapter: 25, question: "A che distanza deve essere posto il triangolo di emergenza in autostrada?", options: ["Almeno 100 m dal veicolo", "Almeno 50 m dal veicolo", "Almeno 150 m dal veicolo", "Almeno 30 m dal veicolo"], correct: 0, explanation: "In autostrada il triangolo deve essere posto ad almeno 100 m dal veicolo fermo, per dare più preavviso agli altri conducenti.", vocab: [{ italian: "triangolo in autostrada", persian: "مثلث در اتوبان" }] },
  { id: 2506, chapter: 25, question: "Qual è la profondità minima del battistrada dei pneumatici?", options: ["1,6 mm", "3 mm", "1 mm", "2 mm"], correct: 0, explanation: "La profondità minima legale del battistrada è 1,6 mm.", vocab: [{ italian: "battistrada minimo", persian: "حداقل آج لاستیک" }] },
  { id: 2507, chapter: 25, question: "Dopo quanti anni dall'immatricolazione è obbligatoria la prima revisione?", options: ["4 anni", "2 anni", "3 anni", "5 anni"], correct: 0, explanation: "La prima revisione periodica si effettua dopo 4 anni dalla prima immatricolazione.", vocab: [{ italian: "prima revisione", persian: "اولین بازرسی دوره‌ای" }] },
  { id: 2508, chapter: 25, question: "All'incrocio senza segnali, chi ha la precedenza?", options: ["Chi proviene da destra", "Chi proviene da sinistra", "Chi è arrivato per primo", "Il veicolo più grande"], correct: 0, explanation: "Senza segnali di precedenza vale la regola della destra: si cede il passo a chi proviene da destra.", vocab: [{ italian: "regola della destra", persian: "قاعده سمت راست" }] },
  { id: 2509, chapter: 25, question: "Fino a quale altezza i bambini devono usare il seggiolino?", options: ["Fino a 150 cm di altezza", "Fino a 12 anni", "Fino a 36 kg di peso", "Fino a 8 anni"], correct: 0, explanation: "I bambini devono usare un seggiolino omologato fino a quando raggiungono i 150 cm di altezza.", vocab: [{ italian: "seggiolino bambini", persian: "صندلی کودک" }] },
  { id: 2510, chapter: 25, question: "Quale limite si applica in autostrada con pioggia?", options: ["100 km/h", "110 km/h", "120 km/h", "130 km/h"], correct: 0, explanation: "In autostrada con pioggia o neve il limite si riduce da 130 a 100 km/h (-30 km/h).", vocab: [{ italian: "autostrada con pioggia", persian: "اتوبان با باران" }] },
  { id: 2511, chapter: 25, question: "Cosa deve fare il tram in un incrocio con altri veicoli?", options: ["Il tram ha sempre la precedenza sui veicoli a motore", "Il tram cede la precedenza come tutti", "Il tram ha precedenza solo se arriva da destra", "Il tram si ferma sempre agli incroci"], correct: 0, explanation: "Il tram ha sempre la precedenza sui veicoli a motore agli incroci, salvo diversa indicazione da segnaletica o agenti.", vocab: [{ italian: "precedenza del tram", persian: "تقدم تراموا" }] },
  { id: 2512, chapter: 25, question: "Qual è la distanza laterale minima per superare un ciclista?", options: ["1,5 metri", "1 metro", "0,5 metri", "2 metri"], correct: 0, explanation: "Quando si supera un ciclista bisogna mantenere una distanza laterale minima di 1,5 metri.", vocab: [{ italian: "distanza dal ciclista", persian: "فاصله از دوچرخه‌سوار" }] },
];
