import type { Question } from "@/lib/types";

export const chapter6Questions: Question[] = [
  { id: 601, chapter: 6, question: "In che parte della carreggiata devono circolare i veicoli?", options: ["Sulla parte destra, vicino al margine destro", "Al centro della carreggiata", "Sulla sinistra, per vedere meglio", "Dove è più conveniente"], correct: 0, explanation: "I veicoli devono sempre circolare sulla parte destra della carreggiata, vicino al margine destro, anche quando la strada è libera.", vocab: [{ italian: "parte destra della carreggiata", persian: "سمت راست جاده" }] },
  { id: 602, chapter: 6, question: "L'inversione di marcia (U-turn) è vietata:", options: ["In autostrada, gallerie, curve, dossi, incroci e dove riduce la visibilità", "Solo in autostrada", "Solo nelle gallerie", "Solo negli incroci con semaforo"], correct: 0, explanation: "L'inversione di marcia è vietata in tutti i luoghi dove potrebbe essere pericolosa: autostrade, gallerie, curve, dossi, incroci e aree con scarsa visibilità.", vocab: [{ italian: "inversione di marcia", persian: "دور زدن" }] },
  { id: 603, chapter: 6, question: "La retromarcia (marcia indietro) in autostrada è:", options: ["Assolutamente vietata", "Permessa per brevi tratti", "Permessa solo di notte", "Permessa solo in caso di emergenza"], correct: 0, explanation: "La retromarcia è assolutamente vietata in autostrada. In autostrada è vietata anche l'inversione di marcia.", vocab: [{ italian: "retromarcia in autostrada", persian: "دنده عقب در اتوبان" }] },
  { id: 604, chapter: 6, question: "Prima di qualsiasi manovra, il conducente deve:", options: ["Accertarsi della fattibilità in sicurezza e segnalare con gli indicatori", "Solo guardare nello specchietto", "Solo azionare gli indicatori di direzione", "Solo aspettare che la strada sia libera"], correct: 0, explanation: "Prima di qualsiasi manovra il conducente deve: accertarsi che sia sicura, segnalare con gli indicatori con anticipo, e non ostacolare/pericolosa gli altri.", vocab: [{ italian: "prima di ogni manovra", persian: "قبل از هر مانور" }] },
  { id: 605, chapter: 6, question: "Per svoltare a sinistra, il conducente deve:", options: ["Dare la precedenza ai veicoli provenienti in senso contrario", "Avere sempre la precedenza assoluta", "Dare la precedenza solo ai pedoni", "Non deve dare la precedenza a nessuno"], correct: 0, explanation: "Chi svolta a sinistra deve dare la precedenza ai veicoli che provengono in senso contrario, oltre che ai pedoni che attraversano.", vocab: [{ italian: "svolta a sinistra", persian: "گردش به چپ" }] },
  { id: 606, chapter: 6, question: "Quando si può occupare la parte sinistra della carreggiata?", options: ["Per sorpassare o svoltare a sinistra", "Sempre, se si è in anticipo sui tempi", "Mai, è sempre vietato", "Solo di notte"], correct: 0, explanation: "La parte sinistra della carreggiata si può occupare solo per sorpassare o per svoltare a sinistra. In tutti gli altri casi si deve stare a destra.", vocab: [{ italian: "parte sinistra della carreggiata", persian: "سمت چپ جاده" }] },
  { id: 607, chapter: 6, question: "Prima di cambiare corsia, il conducente deve:", options: ["Verificare che sia sicuro, poi segnalare con l'indicatore", "Solo segnalare con l'indicatore", "Solo verificare che sia sicuro", "Non è necessario segnalare se c'è poco traffico"], correct: 0, explanation: "Prima di cambiare corsia bisogna: verificare dalla visuale e dagli specchietti che sia sicuro, poi segnalare con l'indicatore prima di iniziare la manovra.", vocab: [{ italian: "cambio di corsia", persian: "تغییر خط" }] },
];
