import type { Question } from "@/lib/types";

export const chapter3Questions: Question[] = [
  { id: 301, chapter: 3, question: "Al semaforo rosso fisso, il conducente deve:", options: ["Fermarsi prima della linea di arresto", "Procedere con cautela", "Rallentare e poi procedere", "Fermarsi solo se ci sono pedoni"], correct: 0, explanation: "Al semaforo rosso è obbligatorio fermarsi PRIMA della linea di arresto. Non si può procedere per nessun motivo tranne in caso di emergenza.", vocab: [{ italian: "semaforo rosso", persian: "سمافور قرمز" }] },
  { id: 302, chapter: 3, question: "Al semaforo giallo fisso, cosa deve fare il conducente?", options: ["Prepararsi a fermarsi; può procedere solo se non riesce a frenare in sicurezza", "Accelerare per passare prima del rosso", "Procedere normalmente perché il giallo non è un divieto", "Fermarsi immediatamente come al rosso"], correct: 0, explanation: "Il giallo indica che il semaforo sta per diventare rosso. Il conducente deve prepararsi a fermarsi. Può procedere solo se la frenata brusca sarebbe pericolosa.", vocab: [{ italian: "semaforo giallo", persian: "سمافور زرد" }] },
  { id: 303, chapter: 3, question: "Al semaforo verde, il conducente:", options: ["Può procedere, rispettando le altre norme (precedenze, pedoni, ecc.)", "Può procedere senza dover rispettare alcun'altra norma", "Ha la precedenza assoluta su tutti", "Può superare il limite di velocità"], correct: 0, explanation: "Il verde permette di procedere, ma non esime dal rispettare le altre norme: precedenze, pedoni, limiti di velocità, ecc.", vocab: [{ italian: "semaforo verde", persian: "سمافور سبز" }] },
  { id: 304, chapter: 3, question: "Il semaforo rosso lampeggiante impone:", options: ["Di rallentare e procedere con prudenza come a un incrocio con STOP", "Di fermarsi e aspettare che diventi verde", "Di procedere normalmente", "Di suonare il clacson e procedere lentamente"], correct: 0, explanation: "Il rosso lampeggiante impone di rallentare e procedere con cautela. Si comporta come un segnale STOP: fermarsi se necessario e dare la precedenza.", vocab: [{ italian: "rosso lampeggiante", persian: "قرمز چشمک‌زن" }] },
  { id: 305, chapter: 3, question: "Il semaforo giallo lampeggiante impone:", options: ["Di rallentare e procedere con prudenza", "Di fermarsi completamente", "Di procedere normalmente senza alcun obbligo", "Di aspettare che diventi verde"], correct: 0, explanation: "Il giallo lampeggiante è un segnale di attenzione. Il conducente deve rallentare e procedere con maggiore prudenza, prestando attenzione ai pericoli.", vocab: [{ italian: "giallo lampeggiante", persian: "زرد چشمک‌زن" }] },
  { id: 306, chapter: 3, question: "Al semaforo per pedoni verde lampeggiante, cosa deve fare un pedone che non ha ancora iniziato ad attraversare?", options: ["Non deve attraversare", "Può attraversare rapidamente", "Può attraversare normalmente", "Deve aspettare il prossimo verde"], correct: 0, explanation: "Il verde lampeggiante per i pedoni indica che il ciclo verde sta per terminare. Chi non ha ancora iniziato NON deve attraversare. Chi ha già iniziato deve affrettarsi.", vocab: [{ italian: "verde lampeggiante pedonale", persian: "سبز چشمک‌زن عابر" }] },
  { id: 307, chapter: 3, question: "Se al semaforo è presente una freccia verde accesa insieme al rosso, cosa indica?", options: ["Si può procedere solo nella direzione indicata dalla freccia verde", "Si può procedere in qualsiasi direzione", "La freccia verde significa semaforo guasto", "Non si deve procedere nonostante la freccia verde"], correct: 0, explanation: "La freccia verde aggiuntiva indica che si può procedere solo nella direzione indicata dalla freccia, anche se il semaforo principale è rosso.", vocab: [{ italian: "freccia verde", persian: "پیکان سبز" }] },
  { id: 308, chapter: 3, question: "I segnali dell'agente di traffico hanno priorità rispetto ai semafori?", options: ["Sì, i segnali dell'agente prevalgono sempre sui semafori e su tutti gli altri segnali", "No, il semaforo ha sempre la priorità", "Solo se l'agente indossa la divisa", "Solo nelle intersezioni senza semafori"], correct: 0, explanation: "L'agente del traffico ha la precedenza assoluta su tutti i segnali, inclusi i semafori. Se un agente indica di procedere nonostante il rosso, si deve obbedire all'agente.", vocab: [{ italian: "agente prevale sul semaforo", persian: "مأمور بر سمافور اولویت دارد" }] },
];
