import type { Question } from "@/lib/types";

export const chapter4Questions: Question[] = [
  { id: 401, chapter: 4, question: "L'agente del traffico alza il braccio verticalmente. Cosa devono fare i veicoli?", options: ["Tutti i veicoli da tutti i lati devono fermarsi", "Solo i veicoli di fronte devono fermarsi", "Solo i veicoli ai lati devono fermarsi", "I veicoli possono procedere lentamente"], correct: 0, explanation: "Il braccio alzato verticalmente ordina a TUTTI i veicoli da tutti i lati di fermarsi. È un ordine di arresto generale.", vocab: [{ italian: "braccio verticale alzato", persian: "دست عمودی بالا" }] },
  { id: 402, chapter: 4, question: "L'agente allunga il braccio orizzontalmente verso i veicoli davanti a lui. Cosa devono fare?", options: ["Fermarsi", "Procedere", "Rallentare", "Dare la precedenza a sinistra"], correct: 0, explanation: "Con il braccio orizzontale, i veicoli davanti e dietro l'agente devono fermarsi. I veicoli ai lati dell'agente possono procedere.", vocab: [{ italian: "braccio orizzontale", persian: "دست افقی" }] },
  { id: 403, chapter: 4, question: "L'agente fa oscillare il braccio dall'alto in basso verso un veicolo. Cosa significa?", options: ["Quel veicolo deve rallentare", "Quel veicolo deve fermarsi immediatamente", "Quel veicolo può accelerare", "Quel veicolo deve svoltare"], correct: 0, explanation: "Il gesto del braccio che oscilla dall'alto in basso è un segnale di rallentamento per il veicolo verso cui è rivolto.", vocab: [{ italian: "braccio oscillato verso il basso", persian: "دست تکان از بالا به پایین" }] },
  { id: 404, chapter: 4, question: "Quando è obbligatorio usare gli indicatori di direzione (frecce)?", options: ["Prima di qualsiasi manovra: svolta, cambio corsia, partenza, sorpasso, arresto", "Solo nelle autostrade", "Solo di notte", "Solo quando ci sono altri veicoli"], correct: 0, explanation: "Gli indicatori di direzione sono obbligatori PRIMA di qualsiasi manovra che comporti un cambiamento di direzione o posizione.", vocab: [{ italian: "indicatori di direzione", persian: "فرچه/راهنما" }] },
  { id: 405, chapter: 4, question: "L'uso del clacson nei centri abitati è:", options: ["Vietato, salvo pericolo imminente", "Libero in qualsiasi momento", "Consentito di giorno ma non di notte", "Consentito per segnalare la propria presenza"], correct: 0, explanation: "Il clacson è vietato nei centri abitati tranne in caso di pericolo imminente. L'uso immotivato è sanzionabile.", vocab: [{ italian: "clacson nei centri abitati", persian: "بوق داخل شهر" }] },
  { id: 406, chapter: 4, question: "Fuori dai centri abitati, il clacson può essere usato per:", options: ["Segnalare la propria presenza in caso di pericolo o prima di un sorpasso", "Salutare altri conducenti", "Accelerare il traffico davanti", "Comunicare con i pedoni"], correct: 0, explanation: "Fuori dai centri abitati il clacson può essere usato per segnalare pericoli o l'intenzione di sorpassare. Non può essere usato in modo superfluo.", vocab: [{ italian: "clacson fuori città", persian: "بوق خارج شهر" }] },
  { id: 407, chapter: 4, question: "I segnali luminosi (lampeggio dei fari abbaglianti) possono essere usati:", options: ["In sostituzione del clacson fuori città, o per segnalare l'intenzione di sorpassare", "Solo in autostrada", "In sostituzione della freccia", "Solo di notte"], correct: 0, explanation: "Il lampeggio dei fari abbaglianti può sostituire il clacson fuori dai centri abitati o essere usato per segnalare la presenza/intenzione di sorpassare.", vocab: [{ italian: "lampeggio abbaglianti", persian: "چشمک چراغ پر" }] },
];
