import type { Question } from "@/lib/types";

export const chapter7Questions: Question[] = [
  { id: 701, chapter: 7, question: "In assenza di segnali all'incrocio, chi ha la precedenza?", options: ["Il veicolo che proviene da destra", "Il veicolo che proviene da sinistra", "Il veicolo più veloce", "Il veicolo che è arrivato per primo"], correct: 0, explanation: "In assenza di segnali di precedenza, vale la 'regola della destra': si cede la precedenza a chi proviene da destra.", vocab: [{ italian: "regola della destra", persian: "قاعده سمت راست" }] },
  { id: 702, chapter: 7, question: "Il tram ha la precedenza rispetto agli altri veicoli?", options: ["Sì, il tram ha sempre la precedenza sui veicoli a motore agli incroci", "No, segue le stesse regole degli altri veicoli", "Solo se ha il semaforo verde", "Solo nelle zone pedonali"], correct: 0, explanation: "Il tram ha sempre la precedenza sui veicoli a motore, salvo diversa indicazione da parte della segnaletica o degli agenti.", vocab: [{ italian: "tram", persian: "تراموا" }] },
  { id: 703, chapter: 7, question: "Entrando in una rotatoria, chi ha la precedenza?", options: ["I veicoli già in circolazione all'interno della rotatoria", "Chi entra nella rotatoria", "Il veicolo più grande", "Il veicolo che viene da destra"], correct: 0, explanation: "All'ingresso della rotatoria si deve dare la precedenza ai veicoli già in circolazione all'interno. La freccia 'Dare Precedenza' è posizionata all'ingresso.", vocab: [{ italian: "rotatoria", persian: "دوار/روتاریا" }] },
  { id: 704, chapter: 7, question: "In quale senso si circola in una rotatoria?", options: ["In senso antiorario (in senso inverso alle lancette dell'orologio)", "In senso orario", "In entrambi i sensi", "Non c'è un senso obbligatorio"], correct: 0, explanation: "Nelle rotatorie si circola sempre in senso antiorario (controrario), intorno all'isola centrale.", vocab: [{ italian: "senso antiorario", persian: "ضد ساعتگرد" }] },
  { id: 705, chapter: 7, question: "Su strade a più corsie, i veicoli devono normalmente:", options: ["Circolaire sulla corsia di destra e usare quelle di sinistra solo per sorpassare", "Circolare sulla corsia centrale", "Scegliere liberamente la corsia", "Usare la corsia di sinistra per andare più veloci"], correct: 0, explanation: "Su strade a più corsie si deve sempre circolare sulla corsia di destra. Le corsie di sinistra si usano solo per sorpassare, poi si rientra a destra.", vocab: [{ italian: "corsia di destra", persian: "خط راست" }] },
  { id: 706, chapter: 7, question: "Cosa indica una corsia riservata ai bus (corsia preferenziale)?", options: ["Solo i mezzi pubblici (bus, taxi se indicato) possono usarla", "Tutti possono usarla se è libera", "Solo i taxi possono usarla", "È una corsia di emergenza"], correct: 0, explanation: "Le corsie riservate (preferenziali) sono riservate ai mezzi di trasporto pubblico (bus, filobus) e ai taxi quando indicato. Gli altri veicoli non possono usarle.", vocab: [{ italian: "corsia preferenziale", persian: "خط اختصاصی اتوبوس" }] },
  { id: 707, chapter: 7, question: "Un veicolo su una strada principale incontra un veicolo su una strada secondaria. Chi ha la precedenza?", options: ["Il veicolo sulla strada principale", "Il veicolo che arriva da destra", "Il veicolo sulla strada secondaria", "Entrambi devono fermarsi"], correct: 0, explanation: "Il veicolo sulla strada principale ha sempre la precedenza su quelli provenienti da strade secondarie, indipendentemente dalla direzione di provenienza.", vocab: [{ italian: "strada principale vs secondaria", persian: "جاده اصلی در مقابل فرعی" }] },
];
