import type { Question } from "@/lib/types";

export const chapter24Questions: Question[] = [
  { id: 2401, chapter: 24, question: "L'assicurazione RC Auto (Responsabilità Civile) è:", options: ["Obbligatoria per tutti i veicoli a motore in circolazione su strade pubbliche", "Facoltativa per i veicoli nuovi", "Obbligatoria solo in autostrada", "Necessaria solo per veicoli commerciali"], correct: 0, explanation: "L'assicurazione RC Auto è OBBLIGATORIA per legge per qualsiasi veicolo a motore che circoli su strade pubbliche.", vocab: [{ italian: "RC Auto obbligatoria", persian: "بیمه RC اجباری" }] },
  { id: 2402, chapter: 24, question: "Cosa copre l'assicurazione RC Auto?", options: ["I danni causati a terzi (persone e cose), ma non al proprio veicolo", "Anche i danni al proprio veicolo", "Solo i danni alle persone", "I danni da eventi naturali"], correct: 0, explanation: "La RC Auto copre esclusivamente i danni causati A TERZI. Per coprire i danni al proprio veicolo serve una polizza Kasko aggiuntiva.", vocab: [{ italian: "cosa copre la RC", persian: "RC چه را پوشش می‌دهد" }] },
  { id: 2403, chapter: 24, question: "Cosa succede se si circola senza assicurazione RC valida?", options: ["Multa elevata e fermo del veicolo", "Solo una multa lieve", "Sospensione della patente di 1 anno", "Niente se non si causa incidenti"], correct: 0, explanation: "Circolare senza RC valida comporta una multa molto elevata e il fermo del veicolo. È un illecito grave.", vocab: [{ italian: "senza assicurazione RC", persian: "بدون بیمه RC" }] },
  { id: 2404, chapter: 24, question: "Dopo quanti anni dalla prima immatricolazione è necessaria la prima revisione periodica?", options: ["4 anni", "2 anni", "3 anni", "5 anni"], correct: 0, explanation: "La prima revisione periodica deve essere effettuata dopo 4 anni dalla prima immatricolazione.", vocab: [{ italian: "prima revisione", persian: "اولین revisione" }] },
  { id: 2405, chapter: 24, question: "Con quale frequenza si effettuano le revisioni periodiche successive alla prima?", options: ["Ogni 2 anni", "Ogni anno", "Ogni 3 anni", "Ogni 4 anni"], correct: 0, explanation: "Dopo la prima revisione (a 4 anni), le revisioni successive si effettuano ogni 2 anni.", vocab: [{ italian: "revisioni successive", persian: "revisioni بعدی" }] },
  { id: 2406, chapter: 24, question: "Cos'è il 'modulo CAI' (Constatazione Amichevole d'Incidente)?", options: ["Un documento che i conducenti coinvolti compilano insieme per descrivere la dinamica", "Il verbale della polizia per incidenti gravi", "Il modulo per rinnovare l'assicurazione RC", "Il documento da presentare in tribunale"], correct: 0, explanation: "Il modulo CAI (modulo blu) è compilato e firmato dalle due parti coinvolte. Velocizza la gestione del sinistro.", vocab: [{ italian: "modulo CAI", persian: "فرم اعلام تصادف دوطرفه" }] },
  { id: 2407, chapter: 24, question: "Cosa si intende per 'omicidio stradale'?", options: ["Il reato penale commesso da chi, violando norme del C.d.S., causa la morte di una persona", "Un incidente mortale fortuito senza responsabilità", "La fuga dopo un incidente con feriti", "Solo gli incidenti causati sotto l'effetto di alcol"], correct: 0, explanation: "L'omicidio stradale (Art. 589-bis C.p.) è un reato penale che si verifica quando una morte è causata da violazione grave del C.d.S.", vocab: [{ italian: "omicidio stradale", persian: "قتل جاده‌ای" }] },
  { id: 2408, chapter: 24, question: "La responsabilità civile per danni causati da un veicolo ricade su:", options: ["Il proprietario del veicolo, anche se non era alla guida", "Solo il conducente al momento dell'incidente", "Solo chi è risultato colpevole", "L'assicurazione, non il proprietario"], correct: 0, explanation: "La responsabilità civile per i danni causati da un veicolo è del PROPRIETARIO, indipendentemente da chi guidava.", vocab: [{ italian: "responsabilità civile del proprietario", persian: "مسئولیت مدنی مالک" }] },
];
