import type { Question } from "@/lib/types";

export const chapter22Questions: Question[] = [
  { id: 2201, chapter: 22, question: "Cosa si intende per 'aquaplaning' (idroplanazione)?", options: ["Il pneumatico perde il contatto con l'asfalto per via di uno strato d'acqua, con perdita totale di controllo", "Un difetto dei pneumatici che causa vibrazioni", "Un sistema di sicurezza attiva che frena automaticamente sul bagnato", "Il movimento laterale del veicolo su fondo bagnato"], correct: 0, explanation: "L'aquaplaning avviene quando tra il pneumatico e l'asfalto si forma uno strato d'acqua che elimina l'aderenza, con conseguente perdita totale di controllo dello sterzo e della frenata.", vocab: [{ italian: "aquaplaning", persian: "آکواپلانینگ" }] },
  { id: 2202, chapter: 22, question: "In caso di aquaplaning, cosa si deve fare?", options: ["Rilasciare gradualmente il gas, non frenare bruscamente e non sterzare", "Frenare al massimo", "Sterzare bruscamente verso il lato opposto", "Accelerare per superare lo strato d'acqua"], correct: 0, explanation: "In caso di aquaplaning: 1) Rilasciare il gas GRADUALMENTE (non di colpo), 2) NON frenare bruscamente, 3) NON sterzare. Attendere che il veicolo recuperi l'aderenza.", vocab: [{ italian: "in caso di aquaplaning", persian: "در صورت آکواپلانینگ" }] },
  { id: 2203, chapter: 22, question: "Come cambia lo spazio di frenata sul ghiaccio rispetto all'asfalto asciutto?", options: ["Può essere fino a 10 volte più lungo", "Raddoppia", "Rimane uguale con l'ABS", "Aumenta del 30%"], correct: 0, explanation: "Sul ghiaccio l'aderenza è minima e lo spazio di frenata può essere fino a 10 volte più lungo rispetto all'asfalto asciutto. L'ABS aiuta ma non elimina il problema.", vocab: [{ italian: "spazio di frenata sul ghiaccio", persian: "فاصله ترمز روی یخ" }] },
  { id: 2204, chapter: 22, question: "In caso di nebbia fitta, quali luci si devono usare?", options: ["Anabbaglianti + fendinebbia anteriori + retronebbia posteriore", "Solo abbaglianti", "Solo luci di posizione", "Abbaglianti + retronebbia"], correct: 0, explanation: "In caso di nebbia: anabbaglianti (non abbaglianti, che riflettono sulla nebbia), fendinebbia anteriori (se la nebbia è intensa) e retronebbia posteriore (per essere visti da dietro).", vocab: [{ italian: "luci in caso di nebbia", persian: "چراغ‌ها در مه" }] },
  { id: 2205, chapter: 22, question: "In galleria, le luci devono essere accese?", options: ["Sì, sempre, anche se la galleria è illuminata", "No, solo nelle gallerie non illuminate", "Solo se la galleria è lunga più di 500 m", "Solo di notte"], correct: 0, explanation: "In galleria le luci devono essere sempre accese, indipendentemente dall'illuminazione della galleria stessa. È un obbligo di legge.", vocab: [{ italian: "luci in galleria", persian: "چراغ در تونل" }] },
  { id: 2206, chapter: 22, question: "Di notte, quando si incontra un veicolo in senso contrario, si deve:", options: ["Passare dagli abbaglianti agli anabbaglianti per non abbagliare il conducente", "Spegnere le luci temporaneamente", "Mantenere gli abbaglianti per essere più visibili", "Lampeggiare con gli abbaglianti"], correct: 0, explanation: "Quando si incontra un veicolo di notte si deve passare dagli abbaglianti agli anabbaglianti per non abbagliare il conducente del veicolo che viene in senso contrario.", vocab: [{ italian: "passare ad anabbaglianti", persian: "تغییر به چراغ کم‌فاصله" }] },
  { id: 2207, chapter: 22, question: "Con nebbia, è consentito sorpassare?", options: ["No, è vietato sorpassare in caso di nebbia", "Sì, se si usa il retronebbia", "Sì, se si usa il clacson", "Sì, ma solo su strade a doppia corsia"], correct: 0, explanation: "Con nebbia è vietato sorpassare perché la visibilità ridotta non permette di vedere eventuali veicoli in senso contrario. Il rischio di incidente frontale è elevatissimo.", vocab: [{ italian: "sorpasso in nebbia", persian: "سبقت در مه" }] },
  { id: 2208, chapter: 22, question: "Cosa è il 'black ice' (ghiaccio nero)?", options: ["Uno strato sottile di ghiaccio quasi invisibile, molto pericoloso", "Il ghiaccio formatosi di notte sulle strade di montagna", "Un tipo di asfalto scivoloso usato nelle gallerie", "Il ghiaccio visibile di colore bianco"], correct: 0, explanation: "Il ghiaccio nero (black ice) è uno strato sottilissimo di ghiaccio trasparente quasi invisibile, che si forma specialmente su ponti e tunnel. È molto pericoloso perché non si vede.", vocab: [{ italian: "black ice / ghiaccio nero", persian: "یخ سیاه (نامرئی)" }] },
];
