import type { Question } from "@/lib/types";

export const chapter11Questions: Question[] = [
  { id: 1101, chapter: 11, question: "Qual è la profondità minima del battistrada dei pneumatici?", options: ["1,6 mm", "3 mm", "1 mm", "4 mm"], correct: 0, explanation: "La profondità minima legale del battistrada è 1,6 mm. Con un battistrada inferiore, i pneumatici non drenano l'acqua correttamente e il veicolo perde aderenza sul bagnato.", vocab: [{ italian: "battistrada", persian: "آج لاستیک" }] },
  { id: 1102, chapter: 11, question: "Cosa causa un gonfiaggio eccessivo dei pneumatici?", options: ["Riduzione della superficie di contatto con l'asfalto e rischio di scoppio", "Maggiore aderenza e sicurezza", "Consumo ridotto di carburante", "Nessun effetto sulla guida"], correct: 0, explanation: "Il gonfiaggio eccessivo riduce la superficie di contatto tra il pneumatico e l'asfalto, aumentando la distanza di frenata. In casi estremi può causare lo scoppio del pneumatico.", vocab: [{ italian: "gonfiaggio eccessivo", persian: "باد زیاد لاستیک" }] },
  { id: 1103, chapter: 11, question: "Cosa causa un gonfiaggio insufficiente dei pneumatici?", options: ["Surriscaldamento, maggior consumo di carburante e rischio di cedimento", "Migliore aderenza", "Minore usura del battistrada", "Nessun effetto pratico"], correct: 0, explanation: "Il gonfiaggio insufficiente causa: maggior consumo di carburante, surriscaldamento del pneumatico, usura irregolare e rischio di cedimento strutturale.", vocab: [{ italian: "gonfiaggio insufficiente", persian: "باد کم لاستیک" }] },
  { id: 1104, chapter: 11, question: "Cosa fa il sistema ABS?", options: ["Impedisce il blocco delle ruote durante la frenata di emergenza, mantenendo il controllo sterzante", "Accelera la frenata in tutte le condizioni", "Distribuisce la forza frenante tra le ruote", "Corregge la traiettoria in curva"], correct: 0, explanation: "L'ABS (Anti-lock Braking System) impedisce che le ruote si blocchino durante una frenata brusca. Questo permette al conducente di mantenere il controllo dello sterzo anche durante la frenata.", vocab: [{ italian: "ABS", persian: "سیستم ضد قفل ترمز" }] },
  { id: 1105, chapter: 11, question: "Come deve essere usato il freno a mano durante la marcia?", options: ["Solo in caso di emergenza (guasto al freno a pedale)", "Normalmente per rallentare", "Mai, è vietato toccarlo durante la marcia", "Per frenate normali in città"], correct: 0, explanation: "Il freno a mano (di stazionamento) è progettato per tenere il veicolo fermo. In marcia va usato SOLO in emergenza (guasto freno principale), azionandolo delicatamente per evitare il bloccaggio delle ruote.", vocab: [{ italian: "freno a mano in marcia", persian: "ترمز دستی در حرکت" }] },
  { id: 1106, chapter: 11, question: "È consentito montare pneumatici di tipo diverso sullo stesso veicolo (es. 2 invernali e 2 estivi)?", options: ["No, è vietato mescolare pneumatici di tipo diverso", "Sì, se si trovano sullo stesso asse", "Sì, se la differenza non è eccessiva", "Sì, è sempre consentito"], correct: 0, explanation: "È vietato montare pneumatici di tipo diverso sullo stesso veicolo. La diversa aderenza potrebbe causare comportamenti imprevedibili, specialmente durante le frenate.", vocab: [{ italian: "mescolare pneumatici", persian: "مخلوط کردن لاستیک‌ها" }] },
  { id: 1107, chapter: 11, question: "Cosa fa l'ESP (Electronic Stability Program)?", options: ["Corregge il sovrasterzo e il sottosterzo, stabilizzando il veicolo in curva", "Aumenta la potenza del motore in salita", "Riduce i consumi", "Distribuisce la forza frenante tra le ruote"], correct: 0, explanation: "L'ESP rileva la perdita di controllo in curva (sovrasterzo o sottosterzo) e interviene frenando singole ruote per correggere la traiettoria e stabilizzare il veicolo.", vocab: [{ italian: "ESP", persian: "سیستم پایداری الکترونیک" }] },
  { id: 1108, chapter: 11, question: "In caso di guasto al sistema frenante, cosa si deve fare?", options: ["Scalare le marce per sfruttare il freno motore e usare con delicatezza il freno a mano", "Accelerare per superare il pericolo più velocemente", "Spegnere il motore immediatamente", "Girare bruscamente il volante"], correct: 0, explanation: "In caso di guasto ai freni: scalare le marce progressivamente (freno motore), usare il freno a mano con molta delicatezza, cercare un'uscita sicura dalla strada.", vocab: [{ italian: "guasto ai freni", persian: "خرابی ترمز" }] },
];
