import type { Question } from "@/lib/types";

export const chapter2Questions: Question[] = [

  { id: 201, chapter: 2, question: "I segnali di pericolo hanno generalmente la forma di:", options: ["Triangolo con bordo rosso", "Cerchio con bordo rosso", "Cerchio con sfondo blu", "Rettangolo con sfondo verde"], correct: 0, explanation: "I segnali di pericolo sono triangoli con bordo rosso. Avvertono il conducente di un pericolo imminente sulla strada (es. curva pericolosa, bambini, animali).", vocab: [{ italian: "segnali di pericolo", persian: "تابلوهای خطر" }] },

  { id: 202, chapter: 2, question: "I segnali di divieto hanno generalmente la forma di:", options: ["Cerchio con bordo rosso su sfondo bianco", "Triangolo con bordo rosso", "Cerchio con sfondo blu", "Rettangolo con sfondo blu"], correct: 0, explanation: "I segnali di divieto sono cerchi con bordo rosso su sfondo bianco (con o senza barra diagonale rossa). Vietano determinati comportamenti al conducente.", vocab: [{ italian: "segnali di divieto", persian: "تابلوهای ممنوعیت" }] },

  { id: 203, chapter: 2, question: "I segnali di obbligo hanno generalmente la forma di:", options: ["Cerchio con sfondo blu", "Triangolo con bordo rosso", "Cerchio con bordo rosso", "Rettangolo con sfondo giallo"], correct: 0, explanation: "I segnali di obbligo sono cerchi con sfondo blu. Impongono al conducente di tenere determinati comportamenti (es. direzione obbligatoria, rotonda obbligatoria).", vocab: [{ italian: "segnali di obbligo", persian: "تابلوهای اجباری" }] },

  { id: 204, chapter: 2, question: "Qual è la gerarchia dei segnali stradali?", options: ["Agente > semaforo > segnale verticale > segnaletica orizzontale", "Semaforo > agente > segnale verticale > segnaletica orizzontale", "Segnale verticale > semaforo > agente > segnaletica orizzontale", "Segnaletica orizzontale > segnale verticale > semaforo > agente"], correct: 0, explanation: "La gerarchia è: (1) Agente del traffico, (2) Semafori, (3) Segnali verticali, (4) Segnaletica orizzontale. L'agente ha sempre la priorità assoluta.", vocab: [{ italian: "gerarchia dei segnali", persian: "اولویت علائم" }] },

  { id: 205, chapter: 2, question: "I segnali temporanei (come quelli dei cantieri) rispetto ai segnali fissi:", options: ["Prevalgono sui segnali fissi", "Hanno la stessa valenza dei segnali fissi", "Hanno meno valenza dei segnali fissi", "Non hanno valenza legale"], correct: 0, explanation: "I segnali temporanei (es. dei cantieri) prevalgono su quelli fissi, perché indicano situazioni di pericolo temporanee che richiedono comportamenti diversi da quelli normali.", vocab: [{ italian: "segnali temporanei", persian: "تابلوهای موقت" }] },

  { id: 206, chapter: 2, question: "Il segnale 'STOP' (ottagonale rosso) impone:", options: ["Di fermarsi completamente prima dell'incrocio, poi dare la precedenza a tutti", "Di rallentare e dare la precedenza solo ai veicoli da destra", "Di fermarsi solo se ci sono altri veicoli in arrivo", "Di dare la precedenza senza necessariamente fermarsi"], correct: 0, explanation: "Il segnale STOP impone di fermarsi COMPLETAMENTE (arresto totale) prima della linea di arresto, poi di dare la precedenza a tutti i veicoli e pedoni.", vocab: [{ italian: "STOP", persian: "توقف کامل اجباری" }] },

  { id: 207, chapter: 2, question: "Il segnale 'Dare Precedenza' (triangolo rosso puntato verso il basso) impone:", options: ["Di cedere il passo a tutti i veicoli sulla strada con precedenza, fermandosi se necessario", "Di fermarsi completamente come allo STOP", "Di rallentare di almeno il 50%", "Di dare precedenza solo ai veicoli da destra"], correct: 0, explanation: "Il segnale 'Dare Precedenza' impone di cedere il passo a tutti i veicoli sulla strada con precedenza. A differenza dello STOP, non è obbligatorio fermarsi se non ce n'è bisogno.", vocab: [{ italian: "dare precedenza", persian: "تقدم دادن" }] },

  { id: 208, chapter: 2, question: "Il segnale 'Divieto di sorpasso' vieta:", options: ["Di sorpassare qualsiasi veicolo a motore, tranne biciclette e ciclomotori in certi casi", "Di sorpassare tutti i veicoli senza eccezioni", "Di sorpassare solo i camion", "Il sorpasso è vietato solo per le motociclette"], correct: 0, explanation: "Il segnale di 'Divieto di sorpasso' vieta di sorpassare qualsiasi veicolo a motore. Eccezioni possibili: biciclette, quando non si occupa la corsia opposta, e altri casi specifici.", vocab: [{ italian: "divieto di sorpasso", persian: "سبقت ممنوع" }] },

  { id: 209, chapter: 2, question: "Un segnale di 'Limite di velocità 50' su sfondo bianco e bordo rosso indica:", options: ["La velocità massima consentita è 50 km/h", "La velocità minima consigliata è 50 km/h", "Si deve rallentare di 50 km/h rispetto alla velocità attuale", "La velocità massima è 50 mph"], correct: 0, explanation: "Il segnale di limite di velocità con cerchio rosso indica la velocità MASSIMA consentita. Il conducente non può superare tale velocità.", vocab: [{ italian: "limite di velocità", persian: "حداکثر سرعت" }] },

  { id: 210, chapter: 2, question: "I segnali di indicazione di colore verde riguardano:", options: ["Le autostrade e le strade extraurbane principali", "Le strade urbane", "Le zone di parcheggio", "I percorsi turistici"], correct: 0, explanation: "I segnali di indicazione con sfondo verde riguardano le autostrade e le strade extraurbane principali. Quelli con sfondo blu riguardano le strade extraurbane ordinarie e urbane.", vocab: [{ italian: "segnali autostradali", persian: "تابلوهای اتوبانی (سبز)" }] },

  { id: 211, chapter: 2, question: "Il segnale 'Senso vietato' (cerchio rosso con barra orizzontale bianca) indica:", options: ["L'accesso è vietato nel senso di marcia indicato dalla freccia sul segnale", "È vietato parcheggiare in quella strada", "La velocità massima è vietata", "È vietato suonare il clacson"], correct: 0, explanation: "Il segnale 'Senso vietato' vieta l'accesso nella direzione che si sta percorrendo. Indica una strada a senso unico in direzione opposta. Non si può entrare.", vocab: [{ italian: "senso vietato", persian: "ورود ممنوع (از جهت مخالف)" }] },

  { id: 212, chapter: 2, question: "Cosa indicano i pannelli integrativi posti sotto i segnali stradali?", options: ["Specificano o limitano il campo di applicazione del segnale principale (es. orario, categoria di veicoli)", "Sono segnali decorativi senza valore legale", "Indicano il nome della strada", "Sostituiscono il segnale principale"], correct: 0, explanation: "I pannelli integrativi (detti anche pannelli complementari) specificano o limitano l'applicazione del segnale a cui si riferiscono, ad esempio indicando l'orario di vigenza o la categoria di veicoli.", vocab: [{ italian: "pannelli integrativi", persian: "پانل‌های تکمیلی" }] },

];
