import type { Question } from "@/lib/types";

export const chapter21Questions: Question[] = [
  { id: 2101, chapter: 21, question: "Cosa si intende per 'guida ecologica' (eco-driving)?", options: ["Una tecnica di guida che riduce i consumi di carburante e le emissioni inquinanti", "Guidare solo veicoli elettrici", "Guidare a bassa velocità in ogni situazione", "Usare solo strade secondarie"], correct: 0, explanation: "L'eco-driving è un insieme di tecniche di guida che permettono di ridurre consumi ed emissioni: anticipare la frenata, cambiare marcia presto, mantenere velocità costante.", vocab: [{ italian: "guida ecologica", persian: "رانندگی اکولوژیک" }] },
  { id: 2102, chapter: 21, question: "Quale abitudine di guida riduce maggiormente i consumi?", options: ["Mantenere una velocità costante ed anticipare le frenate", "Accelerare rapidamente e poi frenare", "Guidare sempre al massimo della marcia", "Usare sempre il freno a mano"], correct: 0, explanation: "Mantenere velocità costante ed anticipare le frenate (freno motore) sono le tecniche più efficaci per ridurre i consumi di carburante.", vocab: [{ italian: "velocità costante", persian: "سرعت ثابت" }] },
  { id: 2103, chapter: 21, question: "L'uso del climatizzatore (aria condizionata) influisce sui consumi?", options: ["Sì, aumenta i consumi del 5-20%", "No, non ha effetti sui consumi", "Sì, ma solo di notte", "Sì, riduce i consumi"], correct: 0, explanation: "Il climatizzatore consuma energia dal motore e aumenta i consumi di carburante tra il 5 e il 20%, a seconda delle condizioni.", vocab: [{ italian: "climatizzatore", persian: "کولر/تهویه هوا" }] },
  { id: 2104, chapter: 21, question: "Cosa produce principalmente il CO₂ emesso dai veicoli?", options: ["La combustione del carburante (benzina o diesel)", "L'attrito dei pneumatici sull'asfalto", "Il sistema di climatizzazione", "Il sistema di frenata"], correct: 0, explanation: "Il CO₂ (anidride carbonica) è il prodotto principale della combustione del carburante. La quantità è direttamente proporzionale al consumo di carburante.", vocab: [{ italian: "CO₂", persian: "دی‌اکسید کربن" }] },
  { id: 2105, chapter: 21, question: "A cosa serve il catalizzatore (marmitta catalitica)?", options: ["Ridurre le emissioni di CO, HC e NOₓ trasformandoli in sostanze meno nocive", "Aumentare la potenza del motore", "Ridurre i consumi di carburante", "Eliminare il rumore del motore"], correct: 0, explanation: "Il catalizzatore trasforma i gas di scarico nocivi (CO, HC, NOₓ) in sostanze meno dannose (CO₂, H₂O, N₂) attraverso reazioni chimiche.", vocab: [{ italian: "catalizzatore", persian: "کاتالیزور" }] },
  { id: 2106, chapter: 21, question: "Quando è consigliabile spegnere il motore?", options: ["Quando si prevede di restare fermi più di 1-2 minuti (es. semaforo lungo)", "Solo quando si parcheggia per più di un'ora", "Mai, perché riaccenderlo consuma più del tenere acceso", "Solo in zone vietate al traffico"], correct: 0, explanation: "Spegnere il motore durante le soste prolungate (> 1-2 minuti) riduce i consumi e le emissioni. Il consumo di riavvio è trascurabile rispetto al tenere il motore al minimo.", vocab: [{ italian: "spegnere il motore", persian: "خاموش کردن موتور" }] },
  { id: 2107, chapter: 21, question: "Come influisce il carico inutile (bagagli pesanti, portapacchi) sui consumi?", options: ["Li aumenta, perché il motore deve fare più lavoro per spostare il peso extra", "Li riduce grazie all'inerzia aggiuntiva", "Non ha effetti apprezzabili", "Li aumenta solo sulle autostrade"], correct: 0, explanation: "Ogni 100 kg di peso extra aumenta i consumi di circa il 5-7%. Il portapacchi sul tetto, anche vuoto, crea resistenza aerodinamica e aumenta i consumi.", vocab: [{ italian: "carico inutile", persian: "بار غیرضروری" }] },
  { id: 2108, chapter: 21, question: "Qual è il gas serra principale emesso dai veicoli?", options: ["CO₂ (anidride carbonica)", "CO (monossido di carbonio)", "NOₓ (ossidi di azoto)", "HC (idrocarburi incombusti)"], correct: 0, explanation: "Il CO₂ è il principale gas serra prodotto dai veicoli a motore, direttamente proporzionale al consumo di carburante. Contribuisce al riscaldamento globale.", vocab: [{ italian: "gas serra", persian: "گاز گلخانه‌ای" }] },
];
