import type { Question } from "@/lib/types";

export const chapter5Questions: Question[] = [
  { id: 501, chapter: 5, question: "Qual è il limite di velocità nei centri abitati?", options: ["50 km/h", "70 km/h", "90 km/h", "30 km/h"], correct: 0, explanation: "Il limite generale nei centri abitati è 50 km/h. Può essere ridotto (es. 30 km/h in zone scolastiche) o aumentato (es. 70 km/h su tangenziali) con apposita segnaletica.", vocab: [{ italian: "centro abitato", persian: "داخل شهر" }] },
  { id: 502, chapter: 5, question: "Qual è il limite di velocità sulle strade extraurbane secondarie?", options: ["90 km/h", "110 km/h", "130 km/h", "70 km/h"], correct: 0, explanation: "Il limite sulle strade extraurbane secondarie (strade statali, provinciali fuori città) è 90 km/h.", vocab: [{ italian: "extraurbana secondaria", persian: "برون‌شهری ثانوی" }] },
  { id: 503, chapter: 5, question: "Qual è il limite di velocità in autostrada?", options: ["130 km/h", "110 km/h", "150 km/h", "90 km/h"], correct: 0, explanation: "Il limite in autostrada è 130 km/h. Si riduce a 100 km/h in caso di pioggia o neve.", vocab: [{ italian: "autostrada", persian: "اتوبان" }] },
  { id: 504, chapter: 5, question: "Quale limite si applica in autostrada con pioggia o neve?", options: ["100 km/h", "110 km/h", "90 km/h", "130 km/h"], correct: 0, explanation: "In autostrada con pioggia o neve il limite si riduce di 30 km/h: da 130 a 100 km/h.", vocab: [{ italian: "pioggia in autostrada", persian: "باران در اتوبان" }] },
  { id: 505, chapter: 5, question: "I neopatentati (patente da meno di 3 anni) qual è il limite massimo in autostrada?", options: ["100 km/h", "110 km/h", "130 km/h", "90 km/h"], correct: 0, explanation: "I neopatentati (prime infrazioni, patente da meno di 3 anni) non possono superare 100 km/h in autostrada e 90 km/h sulle strade extraurbane.", vocab: [{ italian: "neopatentati", persian: "نوپاتنت (۳ سال اول)" }] },
  { id: 506, chapter: 5, question: "Se la velocità raddoppia, lo spazio di frenata:", options: ["Quadruplica", "Raddoppia", "Triplica", "Rimane uguale"], correct: 0, explanation: "Lo spazio di frenata è proporzionale al quadrato della velocità. Se la velocità raddoppia, lo spazio di frenata quadruplica.", vocab: [{ italian: "spazio di frenata", persian: "فاصله ترمز" }] },
  { id: 507, chapter: 5, question: "Lo spazio di arresto è composto da:", options: ["Spazio di reazione + spazio di frenata", "Solo spazio di frenata", "Solo spazio di reazione", "Spazio di frenata - spazio di reazione"], correct: 0, explanation: "Lo spazio di arresto totale è la somma dello spazio di reazione (il tempo che passa prima di premere il freno) e dello spazio di frenata (da quando si preme il freno all'arresto completo).", vocab: [{ italian: "spazio di arresto", persian: "فاصله توقف" }] },
  { id: 508, chapter: 5, question: "Quale limite di velocità si applica su strade extraurbane secondarie con pioggia?", options: ["70 km/h", "90 km/h", "80 km/h", "60 km/h"], correct: 0, explanation: "Con pioggia su strade extraurbane il limite si riduce di 20 km/h: da 90 a 70 km/h.", vocab: [{ italian: "pioggia su extraurbana", persian: "باران در برون‌شهری" }] },
  { id: 509, chapter: 5, question: "Il conducente deve sempre adeguare la velocità a:", options: ["Le condizioni della strada, del traffico, del meteo e della visibilità", "Solo al limite di velocità indicato", "Solo alle condizioni meteo", "La velocità degli altri veicoli"], correct: 0, explanation: "Il conducente deve sempre adeguare la velocità alle condizioni reali: stato della strada, traffico, condizioni atmosferiche e visibilità, anche se è al di sotto del limite.", vocab: [{ italian: "adeguare la velocità", persian: "تطبیق سرعت با شرایط" }] },
  { id: 510, chapter: 5, question: "Qual è il limite di velocità sulle strade extraurbane principali?", options: ["110 km/h", "130 km/h", "90 km/h", "100 km/h"], correct: 0, explanation: "Il limite sulle strade extraurbane principali (con carreggiate separate) è 110 km/h.", vocab: [{ italian: "extraurbana principale", persian: "برون‌شهری اصلی" }] },
];
