import type { Question } from "@/lib/types";

export const chapter9Questions: Question[] = [
  { id: 901, chapter: 9, question: "Qual è il limite legale del tasso alcolemico per un conducente adulto con esperienza?", options: ["0,5 g/l", "0,8 g/l", "0 g/l", "1,0 g/l"], correct: 0, explanation: "Il limite legale di tasso alcolemico per i conducenti adulti con esperienza è 0,5 g/l. Superare questo valore è reato.", vocab: [{ italian: "tasso alcolemico", persian: "سطح الکل خون" }] },
  { id: 902, chapter: 9, question: "Qual è il limite alcolemico per i neopatentati (prime 3 anni)?", options: ["0 g/l (tolleranza zero)", "0,5 g/l", "0,2 g/l", "0,3 g/l"], correct: 0, explanation: "Per i neopatentati (patente da meno di 3 anni), i conducenti under 21 e i conducenti professionali il limite è zero. Non possono aver consumato alcol.", vocab: [{ italian: "neopatentati e alcol", persian: "نوپاتنت و الکل" }] },
  { id: 903, chapter: 9, question: "È vietato guidare sotto l'influenza di droghe?", options: ["Sì, assolutamente vietato senza alcuna soglia minima", "No, solo se il tasso supera una certa soglia", "Solo per alcune categorie di droghe", "Solo se combinato con alcol"], correct: 0, explanation: "Guidare sotto l'influenza di droghe o sostanze psicotrope è assolutamente vietato, senza soglia minima. Anche tracce minime comportano il reato.", vocab: [{ italian: "droghe alla guida", persian: "مواد مخدر پشت فرمان" }] },
  { id: 904, chapter: 9, question: "L'uso del telefono cellulare durante la guida (tenuto in mano):", options: ["È vietato e comporta sanzione e decurtazione punti", "È permesso se si guida lentamente", "È permesso per chiamate brevi", "È vietato solo in autostrada"], correct: 0, explanation: "L'uso del cellulare in mano durante la guida è assolutamente vietato. Comporta sanzione amministrativa e decurtazione di punti dalla patente. In caso di recidiva: sospensione della patente.", vocab: [{ italian: "cellulare alla guida", persian: "موبایل پشت فرمان" }] },
  { id: 905, chapter: 9, question: "In caso di sonnolenza durante la guida, cosa si deve fare?", options: ["Fermarsi in un'area di sosta e riposare", "Bere un caffè e continuare", "Aprire il finestrino e aumentare la velocità", "Fermarsi solo se c'è un autogrill vicino"], correct: 0, explanation: "La sonnolenza è una delle cause principali di incidenti. In caso di sonnolenza si deve FERMARSI in un'area di sosta sicura e riposare. Non si deve guidare senza essere in condizioni adeguate.", vocab: [{ italian: "sonnolenza alla guida", persian: "خواب‌آلودگی پشت فرمان" }] },
  { id: 906, chapter: 9, question: "Come influisce l'alcol sulla guida?", options: ["Riduce i tempi di reazione, altera la percezione e provoca sonnolenza", "Aumenta la concentrazione", "Migliora i riflessi", "Non ha effetti dimostrati sulla guida"], correct: 0, explanation: "L'alcol riduce significativamente i tempi di reazione, altera la percezione delle distanze e velocità, aumenta l'aggressività, riduce la concentrazione e provoca sonnolenza.", vocab: [{ italian: "effetti dell'alcol", persian: "تأثیرات الکل" }] },
  { id: 907, chapter: 9, question: "Prima di prendere un farmaco che potrebbe influire sulla guida, il conducente deve:", options: ["Leggere il foglietto illustrativo e consultare il medico", "Prendere il farmaco solo se la dose è bassa", "Guidare più lentamente", "Non ci sono precauzioni necessarie per i farmaci"], correct: 0, explanation: "Alcuni farmaci (antistaminici, ansiolitici, ecc.) possono ridurre la capacità di guida. Il conducente deve leggere il foglio illustrativo e consultare il medico prima di guidare.", vocab: [{ italian: "farmaci e guida", persian: "داروها و رانندگی" }] },
  { id: 908, chapter: 9, question: "Il vivavoce (kit mains-free) al telefono durante la guida:", options: ["È consentito, ma riduce comunque la concentrazione", "È equiparato all'uso del cellulare in mano ed è vietato", "È sempre permesso senza limitazioni", "È vietato solo in autostrada"], correct: 0, explanation: "Il vivavoce è consentito legalmente, ma studi dimostrano che riduce comunque la concentrazione. L'uso del telefono in mano rimane assolutamente vietato.", vocab: [{ italian: "vivavoce", persian: "بلندگو (hands-free)" }] },
];
