import type { Question } from "@/lib/types";

export const chapter23Questions: Question[] = [
  { id: 2301, chapter: 23, question: "Quale percentuale degli incidenti stradali è causata dal fattore umano?", options: ["Circa il 90%", "Circa il 50%", "Circa il 30%", "Circa il 70%"], correct: 0, explanation: "Circa il 90% degli incidenti stradali è causato da errori umani: velocità eccessiva, distrazione, alcol, mancato rispetto della precedenza, stanchezza.", vocab: [{ italian: "fattore umano negli incidenti", persian: "عامل انسانی در تصادفات" }] },
  { id: 2302, chapter: 23, question: "Quale fascia d'età ha il rischio più elevato di incidenti mortali?", options: ["18-24 anni", "35-45 anni", "50-60 anni", "65+ anni"], correct: 0, explanation: "I giovani tra 18 e 24 anni hanno un rischio di morire in incidente circa 3 volte superiore alla media, a causa di inesperienza, velocità eccessiva e comportamenti a rischio.", vocab: [{ italian: "giovani e incidenti", persian: "جوانان و تصادفات" }] },
  { id: 2303, chapter: 23, question: "Qual è la differenza tra sicurezza attiva e passiva?", options: ["Attiva: evita l'incidente (ABS, ESP); Passiva: riduce i danni (cinture, airbag)", "Attiva: riduce i danni; Passiva: evita l'incidente", "Sono la stessa cosa con nomi diversi", "Attiva: per i pedoni; Passiva: per i conducenti"], correct: 0, explanation: "Sicurezza ATTIVA = tecnologie che EVITANO l'incidente (ABS, ESP, lane assist). Sicurezza PASSIVA = sistemi che RIDUCONO I DANNI se l'incidente avviene (cinture, airbag, rollbar).", vocab: [{ italian: "sicurezza attiva vs passiva", persian: "ایمنی فعال در مقابل منفعل" }] },
  { id: 2304, chapter: 23, question: "Quale fascia oraria è statisticamente più pericolosa per gli incidenti?", options: ["Venerdì e sabato notte (tra le 18:00 e le 6:00)", "Lunedì mattina (traffico intenso)", "Giovedì pomeriggio", "Domenica mattina"], correct: 0, explanation: "Le notti del venerdì e del sabato sono le più pericolose statisticamente, a causa dell'alcol, della stanchezza e dell'alta velocità praticate durante le ore notturne del weekend.", vocab: [{ italian: "fascia oraria pericolosa", persian: "ساعات خطرناک‌تر" }] },
  { id: 2305, chapter: 23, question: "Perché i motociclisti sono considerati utenti ad alto rischio?", options: ["Mancano di protezioni passive (carrozzeria, airbag) ed è più difficile vederli", "Guidano sempre a velocità eccessiva", "Non devono rispettare le stesse norme degli automobilisti", "Perché non usano le cinture di sicurezza"], correct: 0, explanation: "I motociclisti sono ad alto rischio perché mancano di protezioni passive (carrozzeria, airbag, cinture). In caso di incidente, l'impatto è diretto. Sono anche meno visibili agli altri conducenti.", vocab: [{ italian: "rischio motociclisti", persian: "ریسک موتورسواران" }] },
  { id: 2306, chapter: 23, question: "L'ABS (Anti-lock Braking System) è un sistema di sicurezza:", options: ["Attiva, perché aiuta a evitare o ridurre l'incidente", "Passiva, perché riduce i danni dopo l'incidente", "Né attiva né passiva", "Passiva, come le cinture"], correct: 0, explanation: "L'ABS è un sistema di sicurezza ATTIVA perché agisce PRIMA dell'incidente, impedendo il blocco delle ruote e mantenendo il controllo del veicolo durante la frenata d'emergenza.", vocab: [{ italian: "ABS come sicurezza attiva", persian: "ABS به عنوان ایمنی فعال" }] },
  { id: 2307, chapter: 23, question: "Quale è la causa principale degli incidenti stradali tra le seguenti?", options: ["Velocità eccessiva o inadeguata alle condizioni", "Guasto meccanico al veicolo", "Condizioni meteo avverse", "Scarsa manutenzione delle strade"], correct: 0, explanation: "La velocità eccessiva o inadeguata è la principale causa di incidenti stradali. Aumenta sia la probabilità di perdere il controllo sia la gravità delle conseguenze.", vocab: [{ italian: "velocità causa di incidenti", persian: "سرعت علت تصادفات" }] },
];
