import type { Question } from "@/lib/types";

export const chapter8Questions: Question[] = [
  { id: 801, chapter: 8, question: "Quando un pedone si trova sulle strisce pedonali, il conducente deve:", options: ["Fermarsi e aspettare che il pedone attraversi", "Procedere con cautela", "Suonare il clacson per avvisare il pedone", "Rallentare ma non fermarsi"], correct: 0, explanation: "Quando un pedone si trova sulle strisce pedonali, il conducente ha l'obbligo ASSOLUTO di fermarsi e lasciarlo attraversare.", vocab: [{ italian: "strisce pedonali", persian: "خط‌کشی عابر پیاده" }] },
  { id: 802, chapter: 8, question: "È consentito sorpassare un veicolo fermo davanti alle strisce pedonali?", options: ["No, è vietato sorpassarlo", "Sì, se non ci sono pedoni che attraversano", "Sì, sempre", "Solo se si suona il clacson"], correct: 0, explanation: "È assolutamente vietato sorpassare un veicolo fermo davanti alle strisce pedonali, perché potrebbe nascondere dei pedoni che stanno attraversando.", vocab: [{ italian: "sorpasso alle strisce", persian: "سبقت پشت خط‌کشی" }] },
  { id: 803, chapter: 8, question: "I pedoni, in assenza di marciapiede, devono camminare:", options: ["Sul lato sinistro della carreggiata (contro il senso di marcia)", "Sul lato destro della carreggiata", "Al centro della carreggiata", "Possono scegliere il lato preferito"], correct: 0, explanation: "In assenza di marciapiede i pedoni devono camminare sul lato sinistro, cioè di fronte al traffico che viene verso di loro. Questo li rende visibili ai conducenti.", vocab: [{ italian: "lato sinistro senza marciapiede", persian: "سمت چپ جاده بدون پیاده‌رو" }] },
  { id: 804, chapter: 8, question: "Quale distanza laterale minima deve mantenere un conducente quando supera un ciclista?", options: ["Almeno 1,5 metri", "Almeno 1 metro", "Almeno 0,5 metri", "Non è specificata per legge"], correct: 0, explanation: "Quando si supera un ciclista è obbligatorio mantenere una distanza laterale minima di 1,5 metri per garantire la sicurezza del ciclista.", vocab: [{ italian: "distanza dal ciclista", persian: "فاصله جانبی از دوچرخه‌سوار" }] },
  { id: 805, chapter: 8, question: "I ciclisti devono usare le piste ciclabili quando sono disponibili?", options: ["Sì, le piste ciclabili sono obbligatorie quando presenti", "No, sono facoltative", "Solo di notte", "Solo nelle città"], correct: 0, explanation: "Le piste ciclabili sono obbligatorie per i ciclisti quando sono presenti. Non possono circolare sulla carreggiata se c'è una pista ciclabile adiacente.", vocab: [{ italian: "pista ciclabile obbligatoria", persian: "مسیر دوچرخه اجباری" }] },
  { id: 806, chapter: 8, question: "Quanti ciclisti possono andare affiancati?", options: ["Massimo 2, e solo quando non arrecano intralcio", "Nessuno, mai affiancati", "Massimo 3", "Non c'è limite"], correct: 0, explanation: "I ciclisti possono andare affiancati in numero massimo di 2, e solo quando non creano intralcio o pericolo per la circolazione.", vocab: [{ italian: "ciclisti affiancati", persian: "دوچرخه‌سواران کنار هم" }] },
  { id: 807, chapter: 8, question: "Di notte, i ciclisti devono:", options: ["Avere luci anteriore e posteriore accese e indossare indumenti catarifrangenti", "Solo avere il casco", "Solo avere le luci accese", "Non ci sono obblighi notturni per i ciclisti"], correct: 0, explanation: "Di notte i ciclisti devono avere la luce anteriore (bianca) e posteriore (rossa) accese, e indossare indumenti retroriflettenti.", vocab: [{ italian: "ciclista di notte", persian: "دوچرخه‌سوار شب" }] },
];
